### ISSUE TITLE
Workaround for discrete optimization?

### ISSUE THREAD

**Issue by iaroslav-ai** [SheffieldML/GPyOpt#10]
Imagine that I build objective function such that internally it discretizes the real input numbers to integer ones (e.g. 1.6 -> 2, 0.3 -> 0 etc) and computes the objective on these discrete values. This way while GPyOpt sees variables as real numbers effectively it does discrete optimization, as I can always discretize found solution while preserving objective value. On the one hand side, it is guaranteed (at least in theory) that in the limit the result of optimization is globally optimal, thus I would expect that result of implicit discrete optimization will also be global. On the other hand side, it is usually assumed that the objective should be Lipschitz continuous (in theory), which it is not for the outlined case, but it might work just fine in practice. Is this the way people adapt Bayesian Optimization to the discrete case or is there something more to it?

**Comment by javiergonzalezh** [comment]
In the devel branch you can use discrete variables. Have a look to the
notebook:

https://github.com/SheffieldML/GPyOpt/blob/devel/manual/GPyOpt_mixed_domain.ipynb

It works by treating all inputs as continuous variables in the model but it
restricts the search in the acquisition function to feasible values of the
domain. This may be a bit inefficient sometimes but worked well in the
examples that we tried.

**Comment by iaroslav-ai** [comment]
I see. Thanks for the quick reply!
