### ISSUE TITLE
The acquisition suggests a exactly same point as previous one.

### ISSUE THREAD

**Issue by mizunowanko** [SheffieldML/GPyOpt#108]
Dear GPyOpt team.
Thank you for producing such a nice library.
It has saved my time a lot!

Now, I'm trying to maximize a function using GPyOpt.
My Problem is that GPyOpt frequently finishes the iteration before the number of iterations reaches the max_iter.
I'm setting the eps = 0.

Below is my code.

```python
domain = [
    {"name": "b", "type": "continuous", "domain": (0.9, 1.1)}
    , {"name": "c", "type": "continuous", "domain": (0.3, 0.4)}
    , {"name": "d", "type": "continuous", "domain": (0.1, 0.2)}
]
bo = BayesianOptimization(
    f=target_func       # The target_func is a complex function using DB connection.
    , model_type='GP'
    , domain=domain
    , num_cores=1
    , maximize=True
)
bo.run_optimization(
    max_iter=100
    , eps=0
)
```

Whenever GPyOpt finishes the iteration, the last two suggested points are exactly the same.
In addition, when I set the eps = -1, GPyOpt doesn't finish the iteration but it suggests all the same points from the middle.
That means the acquisition can suggest precisely the same point as previous one.
In my understanding, the aquisition never suggests the already suggested points because the posterior probability of the points are 0.

The behavior I mentioned is normal or some bug?

Thanks,
mizunowanko.

**Comment by javiergonzalezh** [comment]
In the new pre-release (see devel branch), we have implemented a de_duplication manager that controls whether you allow the optimization to collect two points a the same location or not. This should solve your issue here.
