### ISSUE TITLE
Large memory usage during optimisation 

### ISSUE THREAD

**Issue by sverzijl** [SheffieldML/GPyOpt#109]
Hi, I have a model with 44 hyperparameters. I am using 'GP_MCMC', 'EI_MCMC', 'Predictive' with 5 initial samples.

After the 5 samples, when I assume it is building the initial model, the memory usage consumes all available ram (32 gb) and CPU usage drops to zero.

Is 44 parameters outside what is computationally feasible? Is there alternative settings that are recommended?

Thanks in advance.

**Comment by javiergonzalezh** [comment]
This was due to the way problems with only categorical/discrete variables were optimized. The code (still in devel) has been refactored now to cover these cases efficiently).
