### ISSUE TITLE
Modelling fail for unnormalised function parameters.

### ISSUE THREAD

**Issue by labodyn** [SheffieldML/GPyOpt#112]
The Gaussian modeling fails for function parameters that are not normalised. I think this is a major flaw. The code below illustrates the problem. The kernels should have a variance that is a similar fraction of the range for both parameters, instead of having equal absolute variance for both parameters.
```python
def f(x):
    x1, x2 = x[0]
    return x1**2 + (x2/100)**2
bounds = [{'name': 'x1', 'type': 'continuous', 'domain': (-1.,1.)}, 
          {'name': 'x2', 'type': 'continuous', 'domain': (-100., 100.)}]
problem = GPyOpt.methods.BayesianOptimization(f, bounds)
problem.plot_acquisition()
```
![bayes_fail](https://user-images.githubusercontent.com/16204193/30651551-568d94de-9e26-11e7-9d4d-17d52a424fa5.png)

**Comment by javiergonzalezh** [comment]
In devel, now you have the option of warping the inputs, which should solve this issue.

**Comment by apaleyes** [comment]
I am going to close this, as warped gp is now available in the main lib
