### ISSUE TITLE
devel branch: some errors and their apparent fixes

### ISSUE THREAD

**Issue by iaroslav-ai** [SheffieldML/GPyOpt#12]
bayesinan_optimization.py:
import deepgp seems to be unused and causes import error on my machine. So far did not experience any problems from commenting it.
ModularBayesianOptimization class initialization does not set initial_iter variable, this causes error in GPyOpt_constrained_optimization.ipynb. With these fixed GPyOpt_constrained_optimization.ipynb seemed to work fine.

**Comment by iaroslav-ai** [comment]
Did not found any other problems with notebooks in manual folder.

**Comment by javiergonzalezh** [comment]
- We are planning to incorporate deep GPs to the current set of available models. I commented it by default anyway until is ready.

- Fixed the issue with the inital_iter variable.

Thanks for pointing it out!
