### ISSUE TITLE
AttributeError when using BayesianOptimization with GP_MCMC

### ISSUE THREAD

**Issue by mozerfazer** [SheffieldML/GPyOpt#121]
Dear developers, I'm using GPyOpt 1.2.0 and I get an error when instantiating BayesianOptimization with a GP_MCMC model. 
```
bo = GPyOpt.methods.BayesianOptimization(
    bb.group_eval,
    domain=bounds,
    model_type='GP_MCMC',
    acquisition_type='EI_MCMC')
```
Here is the error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-150-e5d21ee5f8e1> in <module>()
      3     domain=bounds,
      4     model_type='GP_MCMC',
----> 5     acquisition_type='EI_MCMC')

~/anaconda/lib/python3.6/site-packages/GPyOpt/methods/bayesian_optimization.py in __init__(self, f, domain, constrains, cost_withGradients, model_type, X, Y, initial_design_numdata, initial_design_type, acquisition_type, normalize_Y, exact_feval, acquisition_optimizer_type, model_update_interval, evaluator_type, batch_size, num_cores, verbosity, verbosity_model, maximize, de_duplication, **kwargs)
    130                 self.model = self._model_chooser()
    131         else:
--> 132             self.model = self._model_chooser()
    133 
    134         # --- CHOOSE the acquisition optimizer_type

~/anaconda/lib/python3.6/site-packages/GPyOpt/methods/bayesian_optimization.py in _model_chooser(self)
    170 
    171     def _model_chooser(self):
--> 172         return self.problem_config.model_creator(self.model_type, self.exact_feval,self.space)
    173 
    174     def _acquisition_chooser(self):

~/anaconda/lib/python3.6/site-packages/GPyOpt/util/arguments_manager.py in model_creator(self, model_type, exact_feval, space)
    104         # --- Initialize GP model with MCMC on the parameters
    105         # --------
--> 106         elif self.model_type == 'GP_MCMC':
    107             self.n_samples = self.kwargs.get('n_samples',10)
    108             self.n_burnin = self.kwargs.get('n_burnin',100)

AttributeError: 'ArgumentsManager' object has no attribute 'model_type'
```
I don't get this error when using a standard GP model. The reason may be that in `util/arguments_manager.py`, line 96, the condition is `if model_type == 'GP'` without `self`. 
Thank you!

**Comment by javiergonzalezh** [comment]
Hi @mozerfazer ,

Thanks for pointing this. The problem are the self. that remain untouched from lines 106-112 in util/arguments_manager.py. It should be:

        elif model_type == 'GP_MCMC':
            n_samples = self.kwargs.get('n_samples',10)
            n_burnin = self.kwargs.get('n_burnin',100)
            subsample_interval = self.kwargs.get('subsample_interval',10)
            step_size = self.kwargs.get('step_size',1e-1)
            leapfrog_steps = self.kwargs.get('leapfrog_steps',20)
            return  GPModel_MCMC(kernel, noise_var, exact_feval, n_samples, self.n_burnin, subsample_interval, step_size, leapfrog_steps, verbosity_model)

Are you happy changing this in the code base  and making a PR? :)

Javier

**Comment by mozerfazer** [comment]
Hi @javiergonzalezh ,
Thank you for prompt answering. I changed lines from 106 onwards as there were many forgotten 'self's. Unfortunately, my PS did not go through all the checks. I am not experienced with git, could you please suggest me what TODO? :) 
Thank you!

**Comment by apaleyes** [comment]
Hey. Don't worry about the checks, this has to do with general test coverage of our codebase, which we need to improve. I've left one comment on your PR.

**Comment by javiergonzalezh** [comment]
Merged already.
