### ISSUE TITLE
initial_design in util.stats?

### ISSUE THREAD

**Issue by qxandy** [SheffieldML/GPyOpt#128]
Sorry I'm new here. I tried to install the package from code, then I found that the function _initial_design()_ only exists in _util.general_, not in _util.stats_. Therefore can I replace the import statements 
`from ..util.stats import initial_design`
with
`from ..util.general import initial_design`
 in _driver.py_ safely?

If you are going to define new _initial_design()_ functions in util.stats(), what will the differences be? 

Thank you!

**Comment by apaleyes** [comment]
Hey @qxandy . This is a bug that we have recently discovered and fixed, but have not released yet. Watch out for the update shortly. In meantime feel free to import it from util.general yourself.

**Comment by apaleyes** [comment]
I believe this should be fixed in version 1.2.1 that we have just released. Can you check please?
