### ISSUE TITLE
Similarity kernel parameter selection

### ISSUE THREAD

**Issue by iaroslav-ai** [SheffieldML/GPyOpt#13]
Assume I want to use some similarity kernel with parameter (e.g. exponent of sq. L2 distance divided by sigma). Do I need to specify explicitly the parameter or is the parameter inferred during the optimization process by GPyOpt, e.g. selecting one which gives best cross validation value for error of mean function on available observations?

**Comment by javiergonzalezh** [comment]
You can do both. By default parameters are estimated using MLE (using a
number of restarts that you can specify) but you can also constraint the
parameter values. For this, you first need to create the bo object and then
access the GPy model and set-up your own configuration. This is a GPy
notebook that details how to handle GPy models that may be useful for you.

http://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/GPy/models_basic.ipynb

Sorry the documentation is not completely clear yet in this respect, by we
are working on improving that.

**Comment by iaroslav-ai** [comment]
Thanks for the clarification!
