### ISSUE TITLE
gpyopt destroys matplotlib for everyone else

### ISSUE THREAD

**Issue by hildensia** [SheffieldML/GPyOpt#130]
Hi,
your call to `matplotlib.use` here:
https://github.com/SheffieldML/GPyOpt/blob/83dd4e6811ee0608932340d643ff3b6f6073163e/GPyOpt/__init__.py#L8

destroys matplotlib for everyone importing it after GPyOpt. Please remove those lines from the package.

**Comment by javiergonzalezh** [comment]
Hi @hildensia,

Good point, can you make a quick PR for that?

Javier

**Comment by apaleyes** [comment]
Actually this is not a simple change, as we need to add this line into all of the notebooks to make sure their output looks the same it used to. If you are still happy to do it - please fire away, otherwise we can cover it as well.

**Comment by apaleyes** [comment]
This is now fixed and release, but please let us know if you still experience an issue
