### ISSUE TITLE
vector valued objective function throws  error

### ISSUE THREAD

**Issue by jz69** [SheffieldML/GPyOpt#133]
The GPyOpt documentation specifies, that the  function to be minimized with Bayesian Optimization requires a 2d array as input argument and shall generate a 2d array as return argument.

I tried to minimize a vector valued function using Bayesian Optimization in GPyOpt (version 1.2.1) and get the following error.
---------------------------------------------------------------------
Code snippet:

import GPyOpt
import GPy

n_dof, n_zern, n_constr = [5, 12, 3]

S = np.random.rand(n_zern,n_dof)
C = np.random.rand(n_constr, n_dof)
x0 = np.random.randn(n_dof,1)/10
z = S@x0

def S_x_eq_z(x):
    """
    simple linear problem to test GPyOpt
    input: (n_dof x 1) array
    return: (n_zern x 1) array
    """
    res = S@x.T - z
    print(x.shape,res.shape)
    # returning res throws following error: 
    # "failed in converting 2nd argument `b' of _flapack.dpotrs to C/Fortran array"
    return res#np.linalg.norm(res)

# Design space: variables
my_domain = [{'name':'var_1','type':'continuous', 'domain': (-1,1), 'dimensionality': n_dof}]
             #{'name':'var_2','type':'discrete', 'domain': (-1,1),'dimensionality': n_zern}]
# Design space: constraints: has to yield a 1-dim array
my_constraints = [{'name':'constr_1', 'constrain':'np.sum(x,axis=1)'}]#'S[:,2].T@x'}]

myBOpt = GPyOpt.methods.BayesianOptimization(f=S_x_eq_z,
                                             domain = my_domain,
                                             constrains = my_constraints,
#                                             initial_design_numdata = 5,
                                             acquisition_type='EI',
                                             exact_feval = False)

max_iter = 5    # maximum number of iterations
max_time = 60   # maximum allowed time
eps = 1e-6      # tolerance, max distance between consicutive evaluations

myBOpt.run_optimization(max_iter,eps=0)
---------------------------------------------------------------------
The thrown error is as follows:
"error: failed in converting 2nd argument `b' of _flapack.dpotrs to C/Fortran array"

This issue may be related to issue#95 
("Supplying function to optimize and initial data (X and Y) for design of experiments using bayesian optimization ")

**Comment by javiergonzalezh** [comment]
Hi @jz69,
The output must be a numpy array of one column and as many rows as points you are evaluating. In this sense, we don't accept 'vector-value' functions, as all outputs must be unidimensional. 

Does this help? just let us know.

**Comment by apaleyes** [comment]
Closing, as Javier gave an answer. Let us know if that didn't help
