### ISSUE TITLE
Checkpointing feature

### ISSUE THREAD

**Issue by mtanti** [SheffieldML/GPyOpt#134]
Is there a way to create checkpoints in GPyOpt so that if the program terminates in the middle of an optimization I can continue running it from where it left off?

**Comment by javiergonzalezh** [comment]
We don't have these at the moment but a way of doing it would be to serialize the model after each iteration. Using the external loop evaluation it shouldn't be too difficult. I would be a nice featurure indeed.

**Comment by apaleyes** [comment]
I don't think we will get around to implement this any time soon. However I would suggest checking out [Emukit](https://github.com/amzn/emukit), a new library which we are now working on. Despite not being available by default, it would be trivial to extend Emukit with this functionality
