### ISSUE TITLE
GPU Parallelization

### ISSUE THREAD

**Issue by aditya-radhakrishnan** [SheffieldML/GPyOpt#137]
It seems like you can do batch parallelization across multiple CPU cores (as detailed here http://nbviewer.jupyter.org/github/SheffieldML/GPyOpt/blob/devel/manual/GPyOpt_parallel_optimization.ipynb), but is there any way to do this across multiple GPU's?

**Comment by theudas** [comment]
Honestly the best way to do this is probably the [external evaluation example](http://nbviewer.jupyter.org/github/SheffieldML/GPyOpt/blob/master/manual/GPyOpt_external_objective_evaluation.ipynb)  
I am using this to spread the optimization across multiple nodes on a hpc.

**Comment by javiergonzalezh** [comment]
Agree! we created that API so you can control the parallelization yourself and don't have to restrict to the GPyOpt implementation.
