### ISSUE TITLE
devel branch: how is optimization of acquisition function over discrete variables done?

### ISSUE THREAD

**Issue by iaroslav-ai** [SheffieldML/GPyOpt#14]
From your previous messages, I understand that in order to deal with discrete parameters you restrict search in the acquisition function only over feasible (discrete) values. As gradient descent is at least not obvious to apply in this case, I assume you use a combination of gradient descent and some smart enumeration of discrete parameters. I would greatly appreciate if you would drop a short message on how specifically you optimize, so that I can understand what I should expect in terms of scalability.

**Comment by javiergonzalezh** [comment]
Exactly, we essentially enumerate the set of possible values of the
discrete variables and for each combination we optimize the acquisition for
the reaming continuous variables. To select the point to sample, we take
best candidate from all the combinations.

We don't expect this to scale well when you have many discrete
variables/values but you can speed-up the search by doing the optimization
in a grid.

**Comment by iaroslav-ai** [comment]
I see. A reasonable approach, as it is important to come up with high quality points to sample for experiments that might take days or even weeks to compute anyway.
Once again, thanks for a quick response!
