### ISSUE TITLE
Calculation of EI

### ISSUE THREAD

**Issue by Alaya-in-Matrix** [SheffieldML/GPyOpt#146]
It seems that in GPyOpt, when calculating the EI acquisition function, the minimum posterior mean is selected as the reference point instead of the best observed function value, why is it so? is there any advantange over using the best observed value?

**Comment by javiergonzalezh** [comment]
Hi @Alaya-in-Matrix ,

You are correct. We are doing that so in case of having noisy data the best current value is corrected by the observed noise. In noisy cases, this is more robust that just taking the best value.
