### ISSUE TITLE
Why this linear problem generates such strange predictions?

### ISSUE THREAD

**Issue by CarrKnight** [SheffieldML/GPyOpt#15]
Hello.

Testing out the **devel** branch on the simplest problem I could find (the function sums up the two input variables):

```
bounds = [{'name': 'var_1', 'type': 'continuous', 'domain': (-1,1)},
          {'name': 'var_2', 'type': 'continuous', 'domain': (-1, 1)}
          ]

def myf(x):
    x = GPyOpt.util.general.reshape(x, 2)
    if x.shape[1] != 2:
        return 'wrong input dimension'
    else:
        x1 = x[:, 0] #column of var1
        x2 = x[:, 1] #column of var2
        return x1+x2

max_iter = 50
import GPyOpt
import numpy as np
myProblem = GPyOpt.methods.BayesianOptimization(myf,bounds)
myProblem.run_optimization(max_iter)
```

When I then call 
`myProblem.plot_acquisition("test.png")`
I get a very weird prediction. The posterior mean is fine, the posterior's standard deviation is way out of proportion and basically random. 

![image](https://cloud.githubusercontent.com/assets/1573967/15192932/6504a3b8-17b3-11e6-8bdb-886a4b230e5e.png)

Am I doing something wrong?

**Comment by javiergonzalezh** [comment]
Hi,

That behaviour is due to numerical issues. Since you are taking exact observations of the objective, it helps to set *exact_feval = True* so the model knows that the noise variance is zero. Try running:

''''
myProblem = GPyOpt.methods.BayesianOptimization(myf,bounds, exact_feval = True)
'''

**Comment by CarrKnight** [comment]
Allright so clearly it has something to do with lack of noise. If I add a bit of gaussian noise around my model, that is if I run:
```
def myf(x):
    x = GPyOpt.util.general.reshape(x, 2)
    if x.shape[1] != 2:
        return 'wrong input dimension'
    else:
        x1 = x[:, 0] #column of var1
        x2 = x[:, 1] #column of var2
        return x1+x2 +np.random.normal(scale=0.1)
```
Then the optimization looks perfect:
![image](https://cloud.githubusercontent.com/assets/1573967/15221754/a9e88f7e-1864-11e6-963e-0aa691e8891a.png)

but if I don't add that random noise and I set the optimization to:
```myProblem = GPyOpt.methods.BayesianOptimization(myf,bounds,exact_feval=True)```
I still get flat out wrong standard deviation and acquisition functions:
![image](https://cloud.githubusercontent.com/assets/1573967/15221814/e644c7d0-1864-11e6-98c4-d049c79df8b4.png)

It seems like setting `exact_feval=True` isn't enough on my side. Can you replicate this problem?

**Comment by javiergonzalezh** [comment]
This is what I get:

![index](https://cloud.githubusercontent.com/assets/6853363/15367111/7bb2fe04-1d1f-11e6-8f02-938b000b47ea.png)

it doesn't seems to be a problem but that may be simply that we are using different initial points and the optimization runs differently. Have you tried to pull GPy? Maybe that helps.

Javier

**Comment by CarrKnight** [comment]
Calling pip update on GPy did indeed fix this. Thanks!
