### ISSUE TITLE
Tutorial has error

### ISSUE THREAD

**Issue by beangoben** [SheffieldML/GPyOpt#154]
Hi, love the great work on GPyOpt.
Found an error in the tutorial "GPyOpt: mixing different types of variables".
(<http://nbviewer.jupyter.org/github/SheffieldML/GPyOpt/blob/master/manual/GPyOpt_mixed_domain.ipynb>)
Tutorial mentions :

> In this example we will work in dimension 5. The fun.

Yet the code is :
```
func  = GPyOpt.objective_examples.experimentsNd.alpine1(input_dim=9) 
```
There are also inconsistencies with the parameter specification.
Did not do a pull request since I want to make sure it is a bug, either in writing or in code.

**Comment by javiergonzalezh** [comment]
Hi @beangoben,

Thanks for your comment. It is a bug so it you can make a PR we'd very happy of merging it.

**Comment by apaleyes** [comment]
Thanks for reporting, fixed now!
