### ISSUE TITLE
no exception raised when provided invalid arguments in constructor

### ISSUE THREAD

**Issue by jjmossel** [SheffieldML/GPyOpt#157]
Great work on GPyOpt. However, it took me while to get it working though since I got a code snippet based on an earlier version and did not immediately realize that some of the constructor arguments are deprecated or renamed.

Instead of silently ignoring these existing arguments (by means of **kwargs) it would save a lot of time if a warning was printed.

**Comment by javiergonzalezh** [comment]
Thanks for your feedback @jjmossel. We'll definitely take this into account in future updates.

**Comment by apaleyes** [comment]
That comment makes a lot of sense and would improve the usability of the library. However, it would require a significant effort, given the amount of arguments GPyOpt now has, and the number of potential conflicts and/or misconceptions that can happen if these params are misspecified.

We are now concentrating our efforts on [Emukit](https://github.com/amzn/emukit), a library for BO as well as other similar methods, which attempts to fix this issue by separating out various elements of the optimization loop. Feel free to give it a try and let us know what you think!

With our focus being on Emukit, I don't believe we will do the update requested here, unless someone comes along with a PR. Therefore, closing.
