### ISSUE TITLE
Link to the mailing list is broken

### ISSUE THREAD

**Issue by sharpsy** [SheffieldML/GPyOpt#158]
The provided link for the mailing list opens:
https://lists.shef.ac.uk/sympa/info/gpyopt-users

The page shows the following errors:
ERROR () - gpyopt-users : unknown list
ERROR (info) - Wrong parameters 

When looking at all mailing lists (https://lists.shef.ac.uk/sympa/lists), there is no mailing list with gpyopt in the name or description.

**Comment by javiergonzalezh** [comment]
Thanks for pointing this out. We need to close those as the issues list seems to be the most effective way of communication. Please just post here if you have any question.

**Comment by apaleyes** [comment]
The link to the mailing list is now removed
