### ISSUE TITLE
Gaussian Process defaults to constant mean and variance throughout the domain

### ISSUE THREAD

**Issue by CarrKnight** [SheffieldML/GPyOpt#16]
This refers to the **devel** branch. Couldn't test this on the master.

I have a 2D optimization problem. Optimize x,y in [0,2000000] over a complicated functions.  After 25 runs GPyOpt stops as having found the "optimum". Now because I optimized this function in other ways I know that not to be true. It seems like the problem is that the optimizer stops too early (25 runs it's just too few) and when I plot the acquisition function I get this very weird and completely wrong posterior:

![optimal_tac_separated_acquisition](https://cloud.githubusercontent.com/assets/1573967/15288514/677ded4e-1b63-11e6-9fda-9bb50d16cb12.png)

This is in spite of the fact that the function is not flat at all. The 25 runs have these inputs:
```
[[  554022.18082771   837330.24086706]
 [  603955.26174629   913575.22736361]
 [  871682.61154303  1208867.22113813]
 [  333424.86148015  1610445.10644461]
 [ 1820857.74113731   729840.13906509]
 [ 1581724.07500661  1087447.33561535]
 [ 1320236.72084362   399413.66943186]
 [ 1252644.39261987   978566.35132267]
 [   41922.88862248   875342.96660996]
 [  959290.22350186  1563699.95650388]
 [   37187.69129177  1120012.7272474 ]
 [ 1436628.17206779   410814.1332408 ]
 [ 1732309.40510174  1813431.75106976]
 [  529015.44987526   692654.54154614]
 [  730317.15687086   471378.82506464]
 [  700758.77014555    32881.55202727]
 [  610413.30341607   717372.31286463]
 [  136686.49824964  1833799.95991568]
 [  461725.79515407   230566.15417022]
 [ 1524996.01465518   248755.38929407]
 [  147287.30588703    99918.38886542]
 [  390810.58866436  1606621.28275969]
 [ 1507735.40298871   803206.42371126]
 [   62073.3998766   1442550.39300023]
 [  344237.59736354   955076.55786266]
 [  344237.59736354   955076.55786266]]
```
And produce a large range of outputs.
```
[[ -5444604.30579861]
 [ -4846435.10319802]
 [ -3813369.21313364]
 [-10871314.33351388]
 [ -4977461.22761602]
 [ -4027234.58931002]
 [ -5891597.80309109]
 [ -4270727.32179308]
 [ -5694584.23650084]
 [ -3711169.85177035]
 [ -5606411.28383687]
 [ -5925348.52915016]
 [ -3583504.2144228 ]
 [ -6236937.05403522]
 [ -8076707.63590015]
 [ -5633996.63497615]
 [ -5932892.03629752]
 [ -7612143.30723312]
 [ -6366437.91667295]
 [ -3475903.3506581 ]
 [ -6581225.39228972]
 [ -6512401.53862414]
 [ -4722818.19982356]
 [ -6185242.92427387]
 [ -9579614.18637638]
 [-10343506.13677566]]
```

You should be able to replicate the same wrong posterior by inputting those numbers  and calling:
```
    optimization = GPyOpt.methods.BayesianOptimization(experiment,
                                                       bounds,
                                                       X=initial_x,
                                                       Y=initial_y
                                                       )
```
Changing normalization, acquisition functions or models have no effect.

**Comment by javiergonzalezh** [comment]
Are you in master or in devel? I assume in master because you are using the bounds, right? I think that the problem is that the parameters of the GP are not correctly tuned: the mean of the GP is zero and the variance small as as as I can see. Can you try to refit the model (with 10 initial optimizations of the paramentes) and run one (BO) optimization step. To check that you can do:

optimization.model.optimize_restarts(10)

Hope it helps, let me know.

**Comment by javiergonzalezh** [comment]
Now that I see it, the optimization stop because your last two evaluations are close but already the last two rows of your X matrix are also quite the same so the kernel matrix is going to be singular. To avoid this you can use a more exploration policy and to increase the tolerance
```
 optimization.run_optimization(max_iter, eps = 1e-5)
```

**Comment by CarrKnight** [comment]
Allright so fiddling with the restarts, the eps and even the choice of optimizer doesn't seem to have any effect.
What does is to change the bounds to be from 0 to 1 (rather than from 0 to 2M) and then re-scaling the inputs within the function to maximize. 
Is it perhaps too large of a gap to optimize the length-scale of the gaussian process kernel? Because I notice it defaults to all 1s as a starting point.

When I rescaled everything from 0 to 1 I got something like this:  
![image](https://cloud.githubusercontent.com/assets/1573967/15386800/9b6768fc-1da1-11e6-8200-11498f470a2d.png)

I also tested the same function with spearmint and I got something like this:  
![image](https://cloud.githubusercontent.com/assets/1573967/15387259/0ef5a002-1da4-11e6-9df1-a3703efd1b29.png)

Which I think it's similar if only a bit smoother. (Spearmint internally rescales floats to go from 0 to 1 as well)

**Comment by lawrennd** [comment]
I'll leave Javier to look, but just to note that we've internally discussed
(some time ago) the idea of using particular defaults, don't know the
details here, but it's clearly something that can be confusing if the
lengthscale is initialised very small relative to the original input scale.

**Comment by javiergonzalezh** [comment]
Exactly, the problem we experienced using particular defaults is that those can work well in a problem but not in others. Something that makes the optimization more robust is to integrate out the acquisition with respect to some priors of the hyper-parameter of the GP. I think that spearmint is actually is doing that by default, which can explain the smother result. You can also try that with GPyOpt. Have a look to this notebook:

https://github.com/SheffieldML/GPyOpt/blob/devel/manual/GPyOpt_integrating_model_hyperparameters.ipynb

Hope it helps!
