### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous.  Use a.any() or a.all() CloseEvent Generated

### ISSUE THREAD

**Issue by BlcaKHat** [SheffieldML/GPyOpt#166]
This is the code which was written in 2015 and was working fine.
But now it's giving me error while loading GUI. this function open the browse folder for selecting file. But it throws rhe error.Does it looks like an numpy error ? or matplot error please help. I am not getting any help from any tutorial.

  File "D:\llfg\hrs\RS Datasets Viewer\OpenImage.py", line 150, in browse
    while (wi < (self.width))  and zero == 0:
ValueError: The truth value of an array with more than one element is ambiguous.
 Use a.any() or a.all()
CloseEvent Generated

def browse(self):
        name = QtGui.QFileDialog.getOpenFileName(None, 'Open File')
        FileName.File = name
        self.lineEdit_5.setText(str(name))
        self.img = open_image(str(name))
        self.modname=name
        self.img.__class__
        (self.height, self.width, self.band) = self.img.shape

        arr = self.img.load()
        arr.__class__
        zero = arr[0][0][0]
        wi = 0
        sa = 0
        while wi < (self.width)  and zero == 0:
            sa = 0
            while sa < (self.height) and zero==0:
                zero = arr[sa][wi][0]
                sa = sa+1
            wi += 1  
                   
        factor = 7.5/zero
        
        x = 0
        bandpath=str(Path.BandFolderPath)
        while x<(self.band):
            bd = factor*arr[:,:,x]
            while bd[0][x]>10 or bd[0][x]<-10:
                bd = bd/1.2
            self.final_image = bd.astype(np.uint8)   
            image_display = Image.fromarray(self.final_image)
            image_display.save(bandpath+"\Band_0"+str(x+1)+".tif")
            x = x+1

**Comment by apaleyes** [comment]
Sorry, I don't understand how is GPyOpt used here. Can you please clarify?

**Comment by apaleyes** [comment]
I am going to close this, as I don't see how this is related to GPyOpt and how we could help. Feel free to reopen if you can elaborate.
