### ISSUE TITLE
PyPi release

### ISSUE THREAD

**Issue by farquet** [SheffieldML/GPyOpt#177]
As @apaleyes mentionned in PR #174, there are a bunch of fixes in master. I also see user facing API changes in master (typo fix in main keyword argument).
Sorry to push for this, but looking forward to see a new release. Maybe 1.3.0 ?

**Comment by farquet** [comment]
Note that PR #143 is also critical for regular pypi users, would be great to have it in the latest release.

**Comment by apaleyes** [comment]
We have just uploaded version 1.2.5 to pipy, and will add a blog post about it shortly. It should contain all latest fixes from PRs. Feel free to grab it.
