### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by FlorianWilhelm** [SheffieldML/GPyOpt#18]
Although the end of lifetime of Python 2.7 is 2020, it is important to be compatible with Python 3 in order to allow projects depending on GPyOpt to upgrade to Python 3. With the help of ``from __future__ import print_function, absolute_import, division`` as well as the ``six`` package it is possible with minimal effort to make the package python 2/3 compatible.

**Comment by javiergonzalezh** [comment]
Hi Florian,

You are totally right. Thanks  so much for your comment and suggestions. We are currently working on a devel branch that, although is not Python 3 compatible yet, we expect it to be before it is released. @mikecroucher has also been looking at this for GPy.

**Comment by FlorianWilhelm** [comment]
Hi @javiergonzalezh,

thanks for your positive reply. If already started working on a branch https://github.com/FlorianWilhelm/GPyOpt/tree/py3_compat
and added first commit that allows to at least import gpyopt. Is this something that could help you?
I am not that familiar with gpyopt but where do you see the difficulties in porting it to Python 3?

Cheers,
Florian

**Comment by javiergonzalezh** [comment]
A while ago @glouppe <https://github.com/glouppe>  and @mikecroucher
<https://github.com/mikecroucher> did some work on the master branch.

@mikecroucher <https://github.com/mikecroucher>, how do you think we should
do this? we should perhaps merge what @glouppe <https://github.com/glouppe>
did. I still need to write some unittest for devel but we can also have a
look to it if you have time.

Thanks for contributing!

Javier

**Comment by avehtari** [comment]
The branch dev-python3 now works with Python 3. It will be hopefully soon merged with devel. GPy also needs some updates which are in a pull request waiting to be merged.

**Comment by javiergonzalezh** [comment]
It is merged now.

**Comment by impredicative** [comment]
`setup.py` doesn't list Python 3 compatibility. It only lists Python 2. This is in the classifier line:

    'Programming Language :: Python :: 2.7',
