### ISSUE TITLE
ValueError: all the input array dimensions except for the concatenation axis must match exactly

### ISSUE THREAD

**Issue by ayushsaklani** [SheffieldML/GPyOpt#185]
So, I am trying Bayesian Optimization on Lstm model. And getting Value error. I am not sure what this error means. I tried changing domain dictionary but still the same error. It is running the  first iteration and then throwing the error. 
This is the function that calls model fit and evaluate it.

    def run_model(batch_size = 100, lookback = 11,nb_epoch = 200, neuron1 = 80, neuron2 = 45,     early_stopping = False, patience = 3, lr = 0.0511,decay =0.655,d1 = 0.1 , d2=0.1):
    
    train_datagen,test_datagen = process_data( batch_size = batch_size, lookback=lookback)
    
    model  = lstm_model(train_datagen,test_datagen, batch_size = batch_size, nb_epoch = nb_epoch, neuron1 = neuron1, neuron2 = neuron2 ,early_stopping = early_stopping,patience = patience,lookback =lookback, features= 1, future_steps = 1, lr = lr,decay = decay, d1 = d1, d2 =d2 )
    evalu = evaluate(model,X=train_datagen,X2=test_datagen, batch_size=batch_size)
    x,y = evalu
    
    print("Evaluation of Train {} Test {}".format(x,y))
    print(' ')
    print(' ')
    return evalu
 

This is the domain that i defined.

bounds = [ {'name':'lr', 'type':'continuous', 'domain':(0.01,0.1)},
           {'name':'decay', 'type':'continuous', 'domain':(0.1,1)},
           {'name':'d1', 'type':'continuous', 'domain':(0.1,0.3)},
           {'name':'d2', 'type':'continuous', 'domain':(0.1,0.3)},
           {'name':'neuron1', 'type':'discrete', 'domain':(50,55,60,65,70,75,80,85,90,95,100)},
           {'name':'neuron2', 'type':'discrete', 'domain':(20,30,35,40,45,50,55,60,65,70)},
           {'name':'nb_epoch', 'type':'discrete', 'domain':(20,30,40,50,60,70,80,90,100,150,200,250,300,350)},
           {'name':'lookback', 'type':'discrete', 'domain':(10)},
           {'name':'batch_size', 'type':'discrete', 'domain':(32,40,50,64,70,80,90,100,128,150,200,256,300,400,512)}
           ]

#### Function to optimize:

def opti(x):
    print(x)
    evalu = run_model(batch_size = int(x[:,8]), lookback = int(x[:,7]),nb_epoch = int(x[:,6]),early_stopping = False ,neuron1 = int(x[:,4]), neuron2 = int(x[:,5]), patience = 3, lr = float(x[:,0]),decay =float(x[:,1]),d1 = float(x[:,2]), d2=float(x[:,3]))
    x, y = evalu
    print("Train loss {} Test loss {}".format(x[0],y[0]))
    print evalu
    return evalu

#### optimizer

 opt_model = GPyOpt.methods.BayesianOptimization(opti,  # function to optimize
                                                     domain=bounds, # box-constrains of the problem
                                                initial_design_numdata = 5,   # Number data initial design
                                             acquisition_type='EI',        # Expected Improvement
                                             exact_feval = False
                                               )
 ## Value Error:
![img](https://user-images.githubusercontent.com/19391609/42091185-93f9078e-7ba4-11e8-946c-0bfef4dda6cd.png)

**Comment by apaleyes** [comment]
It looks like your objective returns output of inconsistent shape. What seems to be happening is that gpyopt tries to evaluate objective 5 times and concat results, and it cannot do so because objective returns answers of different shapes. So your debugging should be focusing on making sure that `evalu` in `return evalu` is always the same shape.

**Comment by ayushsaklani** [comment]
evalu returns tuple of 2 arrays having 3 values each [loss accuracy mae] of train and test set. 
I tried to run it with only train set output but still the same error.
