### ISSUE TITLE
How to continue when the objective function solver (e.g., a complex simulation) fails?

### ISSUE THREAD

**Issue by Tony-Chiong** [SheffieldML/GPyOpt#195]
Suppose the objective (a complex simulation) will fail in certain locations, but the locations are unknown. Then How to make the optimization continue？

(GPyOpt can deal with the situation which the objective is known to fail in certain locations: http://nbviewer.jupyter.org/github/SheffieldML/GPyOpt/blob/devel/manual/GPyOpt_external_objective_evaluation.ipynb)

**Comment by apaleyes** [comment]
Is the approach described in this notebook acceptable for you? If so, you can modify it very slightly by maintaining a running list of places where your simulation failed, and passing this list to the `suggest_next_locations` each time it is called. Or am I missing the point of your question?

If you want GPyOpt to handle the whole loop, then currently library does not have a way around failures.

**Comment by Tony-Chiong** [comment]
> Is the approach described in this notebook acceptable for you? If so, you can modify it very slightly by maintaining a running list of places where your simulation failed, and passing this list to the `suggest_next_locations` each time it is called. Or am I missing the point of your question?
> 
> If you want GPyOpt to handle the whole loop, then currently library does not have a way around failures.

The approach described in the notebook only works when we have already known the places where the simulation fails. However, we have no knowledge about the failed places before we start a optimization task. 
If GPyOpt can pass the failed places and continue, we can add the places into a running list and prevent GPyOpt access to these places. I was wondering if this method is feasible.
Thanks. @apaleyes

**Comment by apaleyes** [comment]
I don't think I follow. In the notebook GPyOpt does not handle the call to the objective, so it won't choke if the objective fails. So you may have something like (oversimplified of course):

```
ignored_X = []
for number of iterations:
    bo = GPyOpt.methods.BayesianOptimization(f = None, domain = domain, X = X_step, Y = Y_step, de_duplication = True)
    next_x = bo.suggest_next_locations(ignored_X = ignored_X)

    next_y = objective_function(next_x)
    if next_y is None:
        # objective failed, add this point to ignored and ask for a different point
        ignored_X.append(next_x)
    else:
        # objective did not fail, add results to the list
        X_step.append(next_x)
        Y_step.append(next_y)
```

So if objective failed, you call gpyopt again with the same list of input/output points as before, but a different list of points to ignore. Essentially since you control the call to the objective, you handle the error yourself.

Does this make sense? Or am I completely missing the point?

**Comment by Tony-Chiong** [comment]
> I don't think I follow. In the notebook GPyOpt does not handle the call to the objective, so it won't choke if the objective fails. So you may have something like (oversimplified of course):
> 
> ```
> ignored_X = []
> for number of iterations:
>     bo = GPyOpt.methods.BayesianOptimization(f = None, domain = domain, X = X_step, Y = Y_step, de_duplication = True)
>     next_x = bo.suggest_next_locations(ignored_X = ignored_X)
> 
>     next_y = objective_function(next_x)
>     if next_y is None:
>         # objective failed, add this point to ignored and ask for a different point
>         ignored_X.append(next_x)
>     else:
>         # objective did not fail, add results to the list
>         X_step.append(next_x)
>         Y_step.append(next_y)
> ```
> So if objective failed, you call gpyopt again with the same list of input/output points as before, but a different list of points to ignore. Essentially since you control the call to the objective, you handle the error yourself.
> 
> Does this make sense? Or am I completely missing the point?

Thanks for your demo. That is exactly what I want.
Also, if we are using the parallel computing with a batch_size, and some items in x_next fail to find their y values, we need to complete the x_next in some way (as the len(x_next) seems to need to be equal to the batch_size):
```
        while len(y_next_ls) < batch_size:
            initial_design_random = GPyOpt.experiment_design.random_design.RandomDesign(space).get_samples(
                init_points_count=1)
            ele = initial_design_random[0]
            try:
                y_ = func.f(ele)
                y_next_ls.append([y_])
                x_next_ls.append(ele)
            except:
                ignored_x_ls.append(ele)

        x_next = np.array(x_next_ls)
        y_next = np.array(y_next_ls)
```
