### ISSUE TITLE
Iterative optimization

### ISSUE THREAD

**Issue by davidenunes** [SheffieldML/GPyOpt#199]
Greetings, I have a use case where I wanted to run the optimization procedure iteratively and was wondering if there is any documented example of this workflow. Suppose I have an expensive target function and can evaluate N points at a time, but I would like to do so without giving control to the GPyOpt loop. 

What I wanted is something along the lines

1. generate N initial points according to some variable space
2. evaluate the value of those points (possibly in parallel) outside the GPyOpt library
3. give those values to the model, update it and return N more points 
4. repeat 

All the libraries I found have this "problem" which is the fact that you have to give control of the expensive evaluation of target function to the library, and I really don't want to do that. 

I could just write a custom BO Modular class based on what's already available, but I was wondering if I could avoid that and use some example that  I could be missing.

Thanks in advance

**Comment by SilverSpirit** [comment]
You might want to take a look at the external objective function evaluation example in the manual
https://github.com/SheffieldML/GPyOpt/blob/master/manual/GPyOpt_external_objective_evaluation.ipynb

**Comment by davidenunes** [comment]
That's exactly what I was looking for :+1:, I suspected you would have considered this case :)

don't know how I missed that,
thank you @SilverSpirit
