### ISSUE TITLE
Optimisation not (always) working

### ISSUE THREAD

**Issue by vlavorini** [SheffieldML/GPyOpt#201]
Hi, I was preparing a didactic notebook, then I found this.

In the following code I try to optimise the defined function, but at some point the process go nuts.

More, the process is not deterministic: different restarts can lead both to a good result and the bad one that you see in the animation.

![out](https://user-images.githubusercontent.com/8724860/47028113-fca0ca00-d168-11e8-9504-c4a67256d5c0.gif)

    def forrester(x):
        return -(6*x-2)**2 * np.sin(12*x-4)

    domain_myF =[{'name': 'var1', 'type': 'continuous', 'domain': (0,1.05)}]

    X_init = np.array([[0.], [0.5] ,[1.05]])
    Y_init = np.sin(X_init)

    iter_count = 30
    current_iter = 0
    X_step = X_init
    Y_step = Y_init
    files=[]
    while current_iter < iter_count:
        print ("iteration ", current_iter)
        bo_step = GPyOpt.methods.BayesianOptimization(f = None, domain = domain_myF, X = X_step, Y = Y_step)
        x_next = bo_step.suggest_next_locations()

        y_next = forrester(x_next)

        X_step = np.vstack((X_step, x_next))
        Y_step = np.vstack((Y_step, y_next))

        if current_iter<10:
            strxFile='opt_0%d'%current_iter
        else:
            strxFile='opt_%d'%current_iter
        files.append(strxFile+".png")
        bo_step.plot_acquisition(filename=strxFile)
        current_iter += 1

Versions:
numpy v1.15.2
matplotlib v3.0.0
GPyOpt  v1.2.5
Python 3.7 on MacOS High Sierra

**Comment by apaleyes** [comment]
I believe this failure mode happens when the model gets inputs that is widely different from the current prior, and thus starts to treat everything as noise. @javiergonzalezh do you have insights about mitigation of this?

**Comment by javiergonzalezh** [comment]
I see a couple of issues here. 
- First, Y_init is not being computed from the Forrester function but initialized as `Y_init = np.sin(X_init)` which confuses the model: it is initialized from data with one function and updated with  data from another one. Try `Y_init = forrester(X_init)`.

- Second, the evaluations of the objective are exact so doing `exact_feval=True` in the `BayesianOptimization` class will help a lot to keep things more stable.

Let us know if this works!

**Comment by javiergonzalezh** [comment]
I see two problems here: First, the function that is passed in the optimization is not the same as the function that is queried to compute the initial points. It should be `Y_init = forrester(X_init)`. Also, the evaluation of the objective is exact so the option `exact_feval=True` needs to be used in the `BayesianOptimization` class to improve stability.

Hope this helps!

**Comment by javiergonzalezh** [comment]
I see two problems here: First, the function that is passed in the optimization is not the same as the function that is queried to compute the initial points. It should be `Y_init = forrester(X_init)`. Also, the evaluation of the objective is exact so the option `exact_feval=True` needs to be used in the `BayesianOptimization` class to improve stability.

Hope this helps!

**Comment by javiergonzalezh** [comment]
I see two problems here: First, the function that is passed in the optimization is not the same as the function that is queried to compute the initial points. It should be `Y_init = forrester(X_init)`. Also, the evaluation of the objective is exact so the option `exact_feval=True` needs to be used in the `BayesianOptimization` class to improve stability.

Hope this helps!

**Comment by apaleyes** [comment]
Apologies, GitHub had some issues operating today, so Javier's answer ended up repeated 4 times. I've removed redundant posts. @vlavorini please let us know if these answers helped!

**Comment by vlavorini** [comment]
Silly me.

Yes, the guilty was the initialization (bad, bad copy-paste). Now it works, even without the `exact_feval=True` option set.
Thank you!

**Comment by apaleyes** [comment]
grand, thanks for the feedback!
