### ISSUE TITLE
Composition of Gaussian Processes

### ISSUE THREAD

**Issue by bensprott** [SheffieldML/GPyOpt#202]
I am interested in the GPyOpt program.  I am wondering if there is any functionality to compose Gaussian Processes in a way that reflects function composition.  I see Gaussian Processes as approximations to functions and so composition should be supported.  Is this something you might consider adding?  Perhaps you could supervise me in adding this functionality myself.

**Comment by apaleyes** [comment]
If anywhere, this would be in GPy, not GPyOpt. You may also want to consider:
* Deep GPs. Not exactly this, but close, see http://inverseprobability.com/talks/notes/deep-gaussian-processes.html.
* Multi-fidelity. GPyOpt cannot do that, but our new library Emukit can, see https://amzn.github.io/emukit/multifidelity-emulation/
