### ISSUE TITLE
Should example from "First Steps" find minimum of a function?

### ISSUE THREAD

**Issue by dims12** [SheffieldML/GPyOpt#207]
Here is what it returning:

![image](https://user-images.githubusercontent.com/5513817/48575468-0b72cc00-e923-11e8-89ba-f61edd727c07.png)

![image](https://user-images.githubusercontent.com/5513817/48575492-19c0e800-e923-11e8-9096-32f015284708.png)

I.e. minimum is not found.

Many runs give a lot of positions of vertical red line. Very rare it is near a minimum. Is this by design?

**Comment by dims12** [comment]
Simultaneously `myBopt.x_opt` looks like containing correct value...

**Comment by apaleyes** [comment]
The red line on the plot is not the location of the optimum. It is the place of where the acquisition recommends to run the objective function next. Depending on the acquisition this could be point of highest variance of the model, point that gives highest probability of improvement, point that reduces entropy the most etc.

In this case 15 iterations is probably a bit too much, as you can see that after about 7-8 iterations good fit is achieved and min is found. But if you run longer, acquisition will try to improve the fit the best it can.

Looking at x_opt and fx_opt is correct way to get the final result, the plot is there for some illustration only.

Does that make sense?
