### ISSUE TITLE
No module named task.cost and a question about bayesian_optimization.py(in methods)

### ISSUE THREAD

**Issue by calm85** [SheffieldML/GPyOpt#21]
Hi!
I have two questions and need help.

1) I have already successfully installed and used GPyOpt-master. Now I wanted to switch to 
GPyOpt-devel. However, I am facing with the following error, although I have installed GPyOpt-devel:

ImportError: No module named task.cost

2) The second question is about docstring in bayesian_optimization.py (in methods of GPyOpt)

"""Main class to initialize a Bayesian Optimization method.
    :param f: function to optimize. It should take 2-dimentional numpy arrays as input and return 2-dimentional outputs (one evaluation per row)."""

I have a numpy array as my input and also a corresponding function evaluation (also in numpy). However, I am confused to define **f** in this way. Could you please help how can I define my **f**.
In the tutorial notebooks there are some analytical functions for illustration purpose and not real data as my case.

Thanks in Advance for your help!

**Comment by javiergonzalezh** [comment]
Hi,

1) I just pulled the last devel version and I can't reproduce the error. Can you post the code you are trying to run so I can have a look?

2) For consistency with GPy inputs (X) and outputs (Y) of the models need to be 2-dimensional numpy arrays. The function that you aim to optimize should work in the same way: either if it takes as input one single observation (array of dimension 1xd, for d the dimension of the problem) or n (array of dimension nxd) the output should be a 2D numpy array with and evaluation in each row. Anyway, in devel we internally correct the dimensions so this shouldn't be a big problem.

Thanks for using GPyOpt! Hope this helps!

Javier

**Comment by calm85** [comment]
Thanks Javier for your reply!
Probably I could not properly express my second question.
Instead of having the analytical form of *F* I have some evaluations of my black-box objective function in the following form:
Y = np.array([y1,y2,...,yn])[:,None]
and I have some corresponding input in the following form:
X = np.array([x1,x2,...,xn])[:,None]

So, If I want to identify the best next evaluating point what should I do? Does the following function work?

myProblem = GPyOpt.methods.BayesianOptimization(f = None,bounds, X = X,Y=Y)
myProblem.run_optimization(max_iter)

**Comment by javiergonzalezh** [comment]
You can simply do:

```
def foo(x):
    return np.ones((x.shape[0],1))

myProblem = GPyOpt.methods.BayesianOptimization(f = foo,  X = X, Y = Y)   
myProblem. suggested_sample
```
When you create the object 'myProblem' you directly optimize the model and the acquisition. The value of the next evaluation in saved in myProblem.suggested_sample. Note that the objective is never evaluated so it should even work for whatever *f* you drop in.

Hope it helps!

Javier
