### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by DavidWalz** [SheffieldML/GPyOpt#213]
I have a GPy model that fits my data rather well. If I let GPyOpt.BayesianOptimization fit my model with the same kernel & kernel settings, the fit is much worse.
How can I pass a GPy.models.GPRegression model to GPyOpt.BayesianOptimization?

**Comment by apaleyes** [comment]
You can pass `model=<your_model_object>` after all positional arguments when creating  GPyOpt.BayesianOptimization. It is an expected part of `kwargs`.
