### ISSUE TITLE
No module named task.cost

### ISSUE THREAD

**Issue by calm85** [SheffieldML/GPyOpt#22]
Hi everyone!
I still have the problem to use the new version of GPyOpt with the following error:
>>> import GPyOpt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.5-x86_64/egg/GPyOpt/__init__.py", line 4, in <module>

  File "build/bdist.macosx-10.5-x86_64/egg/GPyOpt/core/__init__.py", line 4, in <module>

  File "build/bdist.macosx-10.5-x86_64/egg/GPyOpt/core/bo.py", line 7, in <module>
ImportError: No module named task.cost

Any idea to resolve this problem?
THANKS

**Comment by calm85** [comment]
Anyone has the similar problem to import GPyOpt?

**Comment by javiergonzalezh** [comment]
I can´t reproduce this. Have you installed the master branch with pip?
Maybe there is a conflict with that when you try to switch branches?

**Comment by calm85** [comment]
Hi Javier!
Could you please give some recommendation to solve this issue? I have already used the previoys version now I am very confused how can I move to the new branch with the above error.
I am a Mac user and always install the python library by "sudo python setup.py install"

**Comment by javiergonzalezh** [comment]
Hi!
Try to clone the repository and switch branches:

```
git clone https://github.com/SheffieldML/GPyOpt.git
cd GPyOpt
git checkout devel
```
Hope it helps, just let me know.

**Comment by calm85** [comment]
Thanks for your reply.
I tried your instruction, but I am still facing with the similar error. :-(

**Comment by javiergonzalezh** [comment]
Have you tried to remove first your previous GPyOpt versions? Perhaps you
have conflicts between them.

**Comment by davek44** [comment]
I have the same problem trying the devel version. I cleaned out the previous installation of the master version using the advice here: http://stackoverflow.com/questions/1550226/python-setup-py-uninstall

**Comment by davek44** [comment]
I figured out the problem. Apparently one does not use "python setup.py install" to install GPyOpt. Instead, you simply add the GPyOpt directory to your $PYTHONPATH. calm85, try clearing out the setuptools installation using the instructions in the link I sent above, cloning a clean repository, and adding it to your $PYTHONPATH.

Javier, it's confusing to have a setup.py script in the directory that one is not supposed to use.

**Comment by jameshensman** [comment]
Javier, you should make use of the setup.py script using the 'develop'
option for in-house development. That effectively adds GPyOpt to the path
(but via a more 'official' route, adding a symlink in site-packages). Then
you should experience the same environment as your users. This works for me
right now on the development branch.

James.

**Comment by zhenwendai** [comment]
That's a very good suggestion. Thanks James! We will do it as soon as 
possible.

Zhenwen

**Comment by javiergonzalezh** [comment]
Good point James. Thanks a lot for the suggestion.

Javier

**Comment by zhenwendai** [comment]
I have updated "setup.py". "python setup.py install" should work now.

**Comment by davek44** [comment]
Thanks for clarifying. Awesome work here, guys!
