### ISSUE TITLE
Using dividing rectangles

### ISSUE THREAD

**Issue by youngapsmikes** [SheffieldML/GPyOpt#221]
## instantiate model 
    model = GPyOpt.models.GPModel(optimize_restarts=5,verbose=False, ARD = True)
    
    ## design space
    design_space = GPyOpt.Design_space(space = space, constraints = constraints)
    
    ## acquisition optimizer 
    aquisition_optimizer = GPyOpt.optimization.AcquisitionOptimizer(space = design_space, optimizer = "DIRECT")
    
    ## acquisition function 
    acquisition = GPyOpt.acquisitions.AcquisitionEI(model, design_space, optimizer=aquisition_optimizer)
    
    ## evaluator 
    evaluator = GPyOpt.core.evaluators.Sequential(acquisition) # Collect points sequentially, no parallelization.

    bo_step = GPyOpt.methods.ModularBayesianOptimization(X_init = X_step, objective = None, Y_init = Y_step,
                                                model = model, space = design_space, acquisition = acquisition, 
                                                evaluator = evaluator)

I want to use the dividing rectangles optimizer with the modular Bayesian optimization functionality. 

However, I get this error 'OptDirect' object has no attribute 'space'. 

Do I need to pass in additional parameters to AcquisitionOptimizer?

**Comment by youngapsmikes** [comment]
The error is being triggered by this line in optimizer.py

"assert self.space.has_types['continuous']"

**Comment by apaleyes** [comment]
Looks like direct optimizer is broken, this line is not necessary and does nothing there. I am going to remove it.

Can you use some other optimizer in meantime?

**Comment by apaleyes** [comment]
In fact I've went ahead and fixed it, it is now merged into master. I have no idea when we are going to put this update in pip, please install from sources if you need this update
