### ISSUE TITLE
LCB acquisition error 

### ISSUE THREAD

**Issue by youngapsmikes** [SheffieldML/GPyOpt#224]
I am getting this error when I use LCB "The set cost function is ignored! LCB acquisition does not make sense with cost." Does anyone have tips?

**Comment by apaleyes** [comment]
It is not an error as such, just a print statement. Somehow the acquisition function gets the parameter in which it cannot make use of, and this message just makes it visible to you.

If you could post your code I might be able to help you further

**Comment by youngapsmikes** [comment]
# Let's load the dataset
    (iter_count, num_init, space, X_train, Y_train, idx) = state 
    
    nfold = 3
    def fit_svr_val(x):
        
        x = np.atleast_2d(np.exp(x))
        fs = np.zeros((x.shape[0],1))
        for i in range(x.shape[0]):
            fs[i] = 0
            for n in range(nfold):
                idx = np.array(range(X_train.shape[0]))
                idx_valid = np.logical_and(idx>=X_train.shape[0]/nfold*n, idx<X_train.shape[0]/nfold*(n+1))
                idx_train = np.logical_not(idx_valid)
                gamma = x[i,2]
                if round(x[i, 2], 5) == 0:
                    gamma = 0.1
                svr = svm.SVR(C=x[i,0], epsilon=x[i,1],gamma=gamma)
                svr.fit(X_train[idx_train],Y_train[idx_train])
                fs[i] += np.sqrt(np.square(svr.predict(X_train[idx_valid])-Y_train[idx_valid]).mean())
            fs[i] *= 1./nfold
        return fs

    Y_all = np.array([]).reshape(0, iter_count+num_init)
    current_iter = 0

    # print(idx, flush = True)
    np.random.seed(idx)

    myBopt = GPyOpt.methods.BayesianOptimization(f=fit_svr_val, domain=space, initial_design_numdata = 2, initial_design_type = 'random', model_type = 'GP', acquisition_type = 'LCB')
    myBopt.run_optimization(max_iter= iter_count)

**Comment by youngapsmikes** [comment]
If I do EI or MPI instead, the code runs fine.

**Comment by apaleyes** [comment]
I've took a deeper look. It's nothing to worry about, costs are not even applied when you are running your code. Just some unfortunate code organization. We may fix it later, but for now this message can be safely ignored in your case

**Comment by samath117** [comment]
This was actually already fixed by this September 2018 commit, which was merged into master: https://github.com/SheffieldML/GPyOpt/pull/190

However, the version of GPyOpt that pip installs by default is prior to this commit (not really sure why, but it is). Make sure to get the latest version by running `pip install git+https://github.com/SheffieldML/GPyOpt.git@master`

**Comment by apaleyes** [comment]
@samath117 thanks, i totally missed this was already fixed. what a shame, i was the one to merge this PR
