### ISSUE TITLE
GPyOpt Constrains - GPyOpt  not running when using modulo '%' Operation in constrains

### ISSUE THREAD

**Issue by rhai6781** [SheffieldML/GPyOpt#225]
I am trying to develop a Convolutional model and optimize it using Bayesian Optimization (GPyOpt). I want to set constrains on the Conv layers strides and Kernel size.  One of the constrains that I want to set is making sure the input of Conv layer can be divided by the strides so the constrain would be 'input%strides'<= 0.  When I add constrains that include addition or subtraction , the optimizer runs fine. But when I include constrains with mod '%' operation, bayesian optimization can't run as if it is blocked. I don't even get any error it just freezes, although the constrain is very simple 'input%strides' . 

Example: if input size =200

bounds = [
          {'name': 'Conv1_strides',        'type': 'discrete',    'domain': list(range(1,301))},
          {'name': 'Conv1_kernelsize',     'type': 'discrete',    'domain': list(range(5,301))}]

constrains= [{'name': 'constr_1',     'constraint':'200%x[:,0]'}]

opt_result= GPyOpt.methods.BayesianOptimization(f=f, domain=bounds,constraints =constrains)

**Comment by beldaz** [comment]
Perhaps this is a problem parsing the `%` symbol. What happens when you replace the modulo operator with an equivalent set of operations `'200 - (200/x[:,0])*x[:,0]'`? Or perhaps to ensure correct handling of integers `'200 - int(math.floor(200/x[:,0]))*x[:,0]'`

**Comment by rhai6781** [comment]
> Perhaps this is a problem parsing the `%` symbol. What happens when you replace the modulo operator with an equivalent set of operations `'200 - (200/x[:,0])*x[:,0]'`? Or perhaps to ensure correct handling of integers `'200 - int(math.floor(200/x[:,0]))*x[:,0]'`

I am unable to use math.floor inside the equation. Getting "NameError: name 'math' is not defined", although I have imported it "import math"

**Comment by beldaz** [comment]
Hmm. So math module can't be imported and used in the constraint string. Hope about casting to ints to ensure integer division? `'200 - (200/int(x[:,0]))*x[:,0]'`

**Comment by beldaz** [comment]
Actually, looking at [`indicator_constraints(self,x)`](https://github.com/SheffieldML/GPyOpt/blob/5aa580f43724fcdf62ac864bf2fdc1b9fcea95ad/GPyOpt/core/task/space.py#L297) the constraint function is just evaluated with `exec()` and shouldn't have any problems with the original form using `%`. However, while testing the behaviour of the code directly works:

```
import numpy as np

def test_const(s,x):
    x = np.atleast_2d(x)
    I_x = np.ones((x.shape[0],1))
    exec('constraint = lambda x:' + s, globals())
    ind_x = (constraint(x) <= 0) * 1
    I_x *= ind_x.reshape(x.shape[0],1)
    return I_x
print(test_const('200%x[:,0]',np.array([[0], [1], [17], [50], [300]])))
#Expect np.array([[1], [1], [0], [1], [0]])
```

Something appears to go wrong when calling it properly:

```
import numpy as np
from GPyOpt.core.task.space import Design_space
def test_indicator_constraints(s, x):
    space = [
        {'name': 'var_1', 'type': 'discrete', 'domain': list(range(1,301))}, # Conv1_strides
        {'name': 'var_2', 'type': 'discrete', 'domain': list(range(5,301))}] # Conv1_kernelsize
    constraints = [{'name': 'const_1', 'constraint': s}]
    design_space = Design_space(space, constraints=constraints)
    I_x = design_space.indicator_constraints(x)
    return I_x

print(test_indicator_constraints('200%x[:,0]', np.array([[0,10], [1,10], [17,10], [50,10], [300,10], [400,10]])))
#    Expect np.array([[1], [1], [0], [1], [0], [0]])

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
```

I don't know why this is, but I suspect it's to do with the result being casted to a positive value that doesn't evaluate to <=0. Offsetting the result by a small amount seems to fix the problem.

```
print(test_indicator_constraints('200%x[:,0] - 0.1', np.array([[0,10], [1,10], [17,10], [50,10], [300,10], [400,10]])))
#    Expect np.array([[1], [1], [0], [1], [0], [0]])
[[1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]]
```

So I think your code is hanging because no values of `x` pass the test due to this evaluation issue. Try changing your constraints to subtract a small amount as shown above, but otherwise keeping the use of `%` the same.

**Comment by rhai6781** [comment]
> Actually, looking at [`indicator_constraints(self,x)`](https://github.com/SheffieldML/GPyOpt/blob/5aa580f43724fcdf62ac864bf2fdc1b9fcea95ad/GPyOpt/core/task/space.py#L297) the constraint function is just evaluated with `exec()` and shouldn't have any problems with the original form using `%`. However, while testing the behaviour of the code directly works:
> 
> ```
> import numpy as np
> 
> def test_const(s,x):
>     x = np.atleast_2d(x)
>     I_x = np.ones((x.shape[0],1))
>     exec('constraint = lambda x:' + s, globals())
>     ind_x = (constraint(x) <= 0) * 1
>     I_x *= ind_x.reshape(x.shape[0],1)
>     return I_x
> print(test_const('200%x[:,0]',np.array([[0], [1], [17], [50], [300]])))
> #Expect np.array([[1], [1], [0], [1], [0]])
> ```
> Something appears to go wrong when calling it properly:
> 
> ```
> import numpy as np
> from GPyOpt.core.task.space import Design_space
> def test_indicator_constraints(s, x):
>     space = [
>         {'name': 'var_1', 'type': 'discrete', 'domain': list(range(1,301))}, # Conv1_strides
>         {'name': 'var_2', 'type': 'discrete', 'domain': list(range(5,301))}] # Conv1_kernelsize
>     constraints = [{'name': 'const_1', 'constraint': s}]
>     design_space = Design_space(space, constraints=constraints)
>     I_x = design_space.indicator_constraints(x)
>     return I_x
> 
> print(test_indicator_constraints('200%x[:,0]', np.array([[0,10], [1,10], [17,10], [50,10], [300,10], [400,10]])))
> #    Expect np.array([[1], [1], [0], [1], [0], [0]])
> 
> [[0.]
>  [0.]
>  [0.]
>  [0.]
>  [0.]
>  [0.]]
> ```
> I don't know why this is, but I suspect it's to do with the result being casted to a positive value that doesn't evaluate to <=0. Offsetting the result by a small amount seems to fix the problem.
> 
> ```
> print(test_indicator_constraints('200%x[:,0] - 0.1', np.array([[0,10], [1,10], [17,10], [50,10], [300,10], [400,10]])))
> #    Expect np.array([[1], [1], [0], [1], [0], [0]])
> [[1.]
>  [1.]
>  [0.]
>  [1.]
>  [0.]
>  [0.]]
> ```
> So I think your code is hanging because no values of `x` pass the test due to this evaluation issue. Try changing your constraints to subtract a small amount as shown above, but otherwise keeping the use of `%` the same.

Thanks, adding the subtraction fixed the problem!

**Comment by apaleyes** [comment]
Thanks @beldaz for your help! I don't believe we will have the capacity to properly investigate and fix this behavior, so the workaround you've suggested is the best option for this use case right now.
