### ISSUE TITLE
Sampling from constrained regions takes long time

### ISSUE THREAD

**Issue by youngapsmikes** [SheffieldML/GPyOpt#226]
Does anyone have a guess on why initial_design takes so long here?
import GPyOpt 

num_init = 2

space =[{'name': 'x1',      'type': 'continuous', 'domain': (-10.,10.)},
               {'name': 'x2','type': 'continuous', 'domain': (-10.,10.)},
               {'name': 'x3',  'type': 'continuous', 'domain': (-10.,10.)},
       {'name': 'x4',  'type': 'continuous', 'domain': (-10.,10.)}
       ]

constraints = [{'name': 'constr_1', 'constraint': 'x[:,1] - 0.60'}, 
               {'name': 'constr_1', 'constraint': '-x[:,1] + 0.57'},
               {'name': 'constr_1', 'constraint': 'x[:,0] - 9.0'}, 
               {'name': 'constr_1', 'constraint': '-x[:,0] + 8.75'},
               {'name': 'constr_1', 'constraint': 'x[:,2] + -1.60'}, 
               {'name': 'constr_1', 'constraint': '-x[:,2] - 1.57'}
              ]
feasible_region = GPyOpt.Design_space(space = space, constraints = constraints)
initial_design = GPyOpt.experiment_design.initial_design('random', feasible_region, num_init)

**Comment by apaleyes** [comment]
So the reason this happens is the way constraints are actually enforced. Simple idea:

0. Until we have requested amount of samples, do:
1. Generate a sample
2. See if it satisfies all constraints
2.1. If it does, add to a list of samples
2.2. If it does not, reject sample
3. Go to 0

So the more constraints there is, and the tighter they are, the longer it may take to generate samples to satisfy them all.

I don't believe there is an easy way to fix this behavior, but if anyone has ideas, please bring them forward.

**Comment by ekalosak** [comment]
Seems like a simple solution might be akin to the following:

- Assume `x\in R^2` for simplicity
- `x0\in [x00, x01]`, `x1\in [x10, x11]`
- `x0+x1\ge 1`

This equates to:

- `x0\in [x00, x01]`
- `x1\in [max(x10, 1-x0), x11]`

And that representation of the valid subspace can be sampled without rejection sampling.
