### ISSUE TITLE
Providing Input Noise to GP

### ISSUE THREAD

**Issue by LarsHH** [SheffieldML/GPyOpt#227]
Hi Everyone,

I'm trying to use Bayesian optimization to optimize this noisy function:

![function](https://user-images.githubusercontent.com/7560290/54754813-ac0f1c00-4ba1-11e9-82c8-245ff388396d.png)

For the regular setup the BO sometimes gets stuck near the optimum. 

![acq_n1](https://user-images.githubusercontent.com/7560290/54754951-001a0080-4ba2-11e9-9ad1-14622917147e.png)

This is improved when I use ten observations per function evaluation and average them. But the optimization usually still doesn't exactly find the minimum. 

![acq_n10](https://user-images.githubusercontent.com/7560290/54754741-7bc77d80-4ba1-11e9-949f-3bd62b0243e5.png)

I am not sure if the model is getting the variance of the observations right. The true standard deviation of the function I used is 1 so standard error of the mean should be ~0.3. But since the plot is scaled it is hard to judge whether that matches the prediction intervals shown in the plot above. Either way, since I have an estimate of the variance of the evaluated points (from the multiple evaluations) I would like to try providing this to the model. Is there a way to do this in GPyOpt? This example has the same variance everywhere but I am also thinking about heteroskedastic functions.

The full example is in https://github.com/LarsHH/sandbox/blob/master/bayesian-optimization.ipynb .

Thanks,
Lars

**Comment by apaleyes** [comment]
Yes, this is possible, if you create your own model with GPy and pass it to GPyOpt.

Heteroskedastic model in GPy: https://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/GPy/heteroscedastic_regression.ipynb

To pass a custom GPy model in GPyOpt, used named "model" argument:
```
GPyOpt.methods.BayesianOptimization(..., model=newGPyModel)
```

**Comment by apaleyes** [comment]
Hey @LarsHH , any chance you could let us know if you resolved your issues?

**Comment by LarsHH** [comment]
Hi Andrei,

I was able to supply the observed variances using the notebook you provided. Thanks. It didn't solve my problem that the Bayesian optimization doesn't always find the minimum for the provided function. But you can close this issue unless you have any other suggestions for the problem I described above.

Thanks,
Lars

**Comment by apaleyes** [comment]
A few more ideas:
* You can use `myBopt.model` object to examine the mean and the variance of the model, to assess if "the model is getting the variance of the observations right."
* BO seems to converge pretty well in your case, even before you implemented heteroskedastic function. Another thing you could do is, after initial BO converged, start a new one on a much smaller interval, say 3.4 to 3.6

In general you would never expect BO to find exact minimum, but rather something in a very close vicinity of it. Besides the objective function is noisy, so it is hard to expect BO to get the exact answer without exact information.

Overall I'd say your notebook does a very good job already.
