### ISSUE TITLE
Unknown constraint optimization?

### ISSUE THREAD

**Issue by fipeop** [SheffieldML/GPyOpt#228]
Hi guys,

Thanks for the amazing work! I have two questions:

1. How do I specify a custom prior for the GP at the beginning of the optimization? Is there a solution using GPopt?
2. Is the  current implementation able to deal with 'unknown' or blackbox constraints (such as a binomial yes/no constraint as in https://arxiv.org/abs/1403.5607)? Or does it just work with explicit constraints?

Thanks!

**Comment by apaleyes** [comment]
Hi there!

1. You would need to create your own GPy model, and set the prior in there. Example code can be found in prior tests: https://github.com/SheffieldML/GPy/blob/devel/GPy/testing/prior_tests.py
Note that it is possible to also create your own prior, if none of existing ones fit your needs.

Then you would need to pass this model to the BayesianOptimization object as a named "model" parameter.

2. Only explicit constraints are supported at the moment.

**Comment by apaleyes** [comment]
I am going to assume these are answered.
