### ISSUE TITLE
Hand over domain to f

### ISSUE THREAD

**Issue by AdministradorViejo** [SheffieldML/GPyOpt#229]
Is it possible to hand over the names of the variables in x to the function f?
Then I could create a dictionary which I want to use later for creating the model.
This would be more dynamic than changing variables every time I change the bounds.

**Comment by AdministradorViejo** [comment]
Or where is x handed over to be evaluated in f in the optimization algorithm?
Yes, I can look it up myself, but haven't found it yet

**Comment by apaleyes** [comment]
I don't think I am following. Can you throw together a few lines of code, to illustrate what you wanted to do?
