### ISSUE TITLE
Massive compute time increase with Local Penalization

### ISSUE THREAD

**Issue by cinaljess** [SheffieldML/GPyOpt#231]
Hello,

  I have been running the offline mode of GPyOpt to simulate batch sampling optimization. This works very well; however, the runtime difference between my two sets of hyperparameters is 2 orders magnitude slower. Thompson sampling is very quick, finishing in less than 5 minutes, while local penalization is taking up to 3 hours on the same data.

I am comparing thompson sampling to local penalization in the below setup.
```python
model = GPyOpt.methods.BayesianOptimization(f=None,
                                            domain=domain, 
                                            batch_size=batch_size,
                                            evaluator_type='thompson_sampling', 
                                            ARD=True,
                                            X=X_step, 
                                            Y=Y_step,
                                            cores=24)
``` 
against
```python
model = GPyOpt.methods.BayesianOptimization(f=None,
                                            domain=domain, 
                                            batch_size=batch_size,
                                            evaluator_type='local_penalization', 
                                            ARD=True,
                                            X=X_step, 
                                            Y=Y_step,
                                            cores=24)
``` 

The batch size is 384, the initial number of samples is 384, and the domain is 19 dimensions. 

Is local penalization expected to take so long? Do you have suggestions on how to speed the calculations up?

**Comment by javiergonzalezh** [comment]
Hi @cinaljess,

In you example, for each batch generation, the local penalization needs to solve 384 optimization problems in 19 dimensions all of which are run several times to avoid local minima. With TS, you are just generating samples from a multivariate Gaussian which is much faster. The local penalization approach is quite efficient for small/moderate sample sizes but for lager batches as the ones you have TS seems a more practical approach.

Hope this helps.

**Comment by cinaljess** [comment]
Thanks for the insight Javier. For this application I get comparable results in simulation using thompson sampling and will use it moving forward.
