### ISSUE TITLE
There is no docs about constraints?

### ISSUE THREAD

**Issue by TX-QAQ** [SheffieldML/GPyOpt#232]
Is it possible to assign boolean type constraint rather than inequality?
e.g. (x[:,0] != 1 or x[:,1]!=2)
// variable x0 x1 cannot be 1,2 at the same time

**Comment by beldaz** [comment]
No, everything has to be specified using inequalities. But you can approximate a Boolean condition. E.g.., https://stackoverflow.com/a/49129040/290182

I suggest you cast the result as an integer, e.g.,
-1 if x[:,0] != 1 or x[:,1]!=2 else 1
Such that the constraint is <0 only when either of your conditions hold.

Documentation is quite sparse, but constraints are described in https://gpyopt.readthedocs.io/en/latest/GPyOpt.core.task.html?highlight=constraint#module-GPyOpt.core.task.space and a good is https://github.com/SheffieldML/GPyOpt/blob/3bd165f349ae4bc37f5b675b4191c0eda5dac070/manual/GPyOpt_constrained_optimization.ipynb

**Comment by TX-QAQ** [comment]
Thanks a lot!
I managed to transform it by convert it into polynomial with magic numbers.
By the way, it's interesting that "if else" statement could be used in a constraint.
