### ISSUE TITLE
Modify design space during optimisation

### ISSUE THREAD

**Issue by beldaz** [SheffieldML/GPyOpt#234]
I am trying to optimise a set of integer parameters for a deep learning model using GPyOpt, by minimising the test loss of a trained model constructed with those parameters. In some situations the loss consistently evaluates to NaN, and I would like to exclude these from the search space since they inconveniently occur close to where the optimum is thought to be. 

In Design_Space::indicator_constraints appears to build a hypercube of the design space and mark any points at which constraints do not hold. Would it be safe to modify the result of this to exclude further specific points? Ideally this would be something done during optimisation as new bad points were discovered - at present the only way I can currently do this is to add additional pointwise constraints and re-run the optimisation after bad points are discovered.

**Comment by beldaz** [comment]
Note that my current approach I am essentially having to loop the optimization process externally, re-using saved evaluations and running `run_optimization(max_iter=1)` after creating pointwise constraints, for any existing evaluations that yielded NaN loss - here's a snippet excluding the outer loop to demonstrate:

```
import GPy, GPyOpt
import logging
from GPyOpt.methods import BayesianOptimization
from GPyOpt.models import GPModel
import pandas as pd
import numpy as np
import math as m

from mycode import vae_eval
# vae_eval(x) builds a model using parameters x, trains it and then returns loss evaluated against a test dataset

evals_filename = '../data/past_evals.txt'
nans_filename = '../data/past_nans.txt'
domain = [
          {'name': 'myvar1',        'type': 'discrete',    'domain': list(range(5,81))},
          {'name': 'myvar2',        'type': 'discrete',    'domain': list(range(1,11))},
          {'name': 'myvar3',     'type': 'discrete',    'domain': list(range(5,81))},
          {'name': 'myvar4',        'type': 'discrete',    'domain': list(range(10,81))},
          {'name': 'myvar5',        'type': 'discrete',    'domain': list(range(1,21))},
          {'name': 'myvar6',     'type': 'discrete',    'domain': list(range(1,61))},
]

# 
# Wrap everything below in a loop to explore multiple locations with GPyOpt, rather than using max_iter
#

gp_Y = None
gp_X = None

try:
    gp_evals = pd.read_csv(evals_filename, delimiter="\t", usecols=['Y', 'var_1','var_2', 'var_3', 'var_4', 'var_5', 'var_6'])
    logging.info("Using previous results in " + evals_filename)
    
    gp_nans = pd.read_csv(nans_filename, delimiter="\t", usecols=['Y', 'var_1','var_2', 'var_3', 'var_4', 'var_5', 'var_6'])
    logging.info("Loaded bad points from " + nans_filename)
    gp_nans.append(gp_evals[gp_evals['Y'].isnull()], ignore_index = True)
    gp_nans.to_csv(nans_filename)
    
    # Exclude NaN locations
    constraints= []
    for i,bad in gp_nans.iterrows():
        constraints.append({'name': 'constr_{}'.format(i),
            'constraint': '(x == [{},{},{},{},{},{}]).all(axis=1)*1 -.5'.format(bad['var_1'], bad['var_2'], bad['var_3'], bad['var_4'], bad['var_5'], bad['var_6'])})

    gp_evals.dropna(inplace=True)
    gp_Y = np.array([[x] for x in gp_evals["Y"]])
    gp_X = np.array(gp_evals.filter(regex="var*"))
except:
    logging.info("No previous evaluation data available, starting from scratch")

opt = BayesianOptimization(f=vae_eval, 
            domain=domain, constraints=constraints, 
            model=GPModel(kernel=GPy.kern.Matern52(input_dim=6, ARD=True)),
            X=gp_X, Y=gp_Y)
opt.run_optimization(max_iter=1, verbosity=False)
opt.save_evaluations(evals_filename)
```

However I think this is awkward and may scale poorly with large numbers of samples.

**Comment by apaleyes** [comment]
Running the loop externally is fine, although we have a better API for that now: `suggest_next_locations`. And I think you should actually look into using it, because it has following parameter: 

```
:param ignored_X: matrix of input configurations that the user black-lists, i.e., those configurations will not be suggested again (default, None).
```

This can be updated in between iterations, and should help you with those points that break the loss evaluation

**Comment by beldaz** [comment]
Sounds very promising. Will look into this API. Thanks!
