### ISSUE TITLE
Strange behavior: seemingly a contradiction in assertions

### ISSUE THREAD

**Issue by KOLANICH** [SheffieldML/GPyOpt#237]
The versions from git are used (255539dc5927819ca701e44fe3d76cd4864222fa and https://github.com/SheffieldML/GPy/commit/54c32d79d289d622fb18b898aee65a2a431d90cf).

My code

```python
#f is set later
optimizer = GPyOpt.methods.BayesianOptimization(f=None, domain=specSeq, ... X=np.empty((0, len(specSeq))), Y=np.empty((0, 1)), ...) 
```

results in

```
  File "%SECRET%\lib\site-packages\GPyOpt\core\bo.py", line 137, in run_optimization
    self._update_model(self.normalization_type)
  File "%SECRET%\lib\site-packages\GPyOpt\core\bo.py", line 249, in _update_model
    Y_inmodel = normalize(self.Y, normalization_type)
  File "%SECRET%\lib\site-packages\GPyOpt\util\general.py", line 215, in normalize
    raise NotImplementedError('Only 1-dimensional arrays are supported.')
NotImplementedError: Only 1-dimensional arrays are supported.
```
If I change to

```python
optimizer = GPyOpt.methods.BayesianOptimization(f=None, domain=specSeq, ... X=np.empty((0, len(specSeq))), Y=np.empty(0), ...) 
```

then I get

```
  File "%SECRET%\lib\site-packages\GPy\core\gp.py", line 48, in __init__
    assert Y.ndim == 2
```

**Comment by apaleyes** [comment]
What happens here is library being confused because it sees empty arrays, which is very unexpected input. Error messages tell you it is confused, but not exactly how.

Basically:

```
>>> np.empty(0).size
0
>>> np.empty((0, 1)).size
0
```

There is no point to pass empty arrays to gpyopt there anyway. What are you trying to achieve with it?

**Comment by KOLANICH** [comment]
I am doing a metaoptimizer (https://gitlab.com/KOLANICH/UniOpt.py, broken, the latest fixes are not there yet, but you can look `backends` dir for the approach used there) and I need to inject points in runtime, so I init the stuff with empty arrays, and then add points if I get them. In the current state adding points in runtime has no benefit as metaoptimizer is not yet implemented, but splitting creation of optimizer object and adding points simplifies gives the cleaner architecture.

**Comment by apaleyes** [comment]
I see. Well, it looks as though you will need to find a way to provide at least one point. To the best of my knowledge, at the moment GPyOpt requires either:
1. At least one initial point provided by the user
2. Input that allows GPyOpt to generate a couple of initial points itself

In theory it should be possible to start the bayes opt loop from nothing, but GPyOpt does not support this edge case.

For you use case I'd also recommend taking a look at external objective evaluation notebook: https://nbviewer.jupyter.org/github/SheffieldML/GPyOpt/blob/master/manual/GPyOpt_external_objective_evaluation.ipynb. It sounds very relevant to what you are doing, and should give you more control over the optimization loop

**Comment by KOLANICH** [comment]
Thanks for the advice, I have solved the issue.
