### ISSUE TITLE
Better explanation of variable types

### ISSUE THREAD

**Issue by LarsHH** [SheffieldML/GPyOpt#238]
Hi there,

This is more of a question rather than an issue. My current understanding is the following:

"continuous": real valued variable
"discrete": discrete valued variable e.g. number of units in neural network. That is, GPyOpt knows that 111 < 112 but only selects integer values.
"bandit": could be used for categorical variables such as activation function in neural network (relu/sigmoid/tanh) if encoded numerically (e.g. relu->1, sigmoid->2, tanh->3) but then in this case 1 not < 2. Is that correct? I am also a bit confused why it seems to only accept a numpy array for the domain.
"categorical": what is the difference to bandit?

Please point me to the appropriate documentation regarding this, but all I could find was https://gpyopt.readthedocs.io/en/latest/GPyOpt.core.task.html?highlight=domain#module-GPyOpt.core.task.variables . 

Thanks,
Lars

**Comment by javiergonzalezh** [comment]
Hi @LarsHH , 

The bandit one is probably a bit confusing here. What we had in mind here are sets of points that you cannot represent using any of the other variables. For instance, in [this](https://github.com/SheffieldML/GPyOpt/blob/master/manual/GPyOpt_bandits_optimization.ipynb) notebook you need to find the city with the maximum temperature in US. You need to optimize for longitude and latitude but only within a predefined set of cities with given locations (which are defined as a numpy array at the beginning of the optimization). This is a very unusual case, actually, so you can probably ignore this type for most of your problems.

**Comment by apaleyes** [comment]
To add to what @javiergonzalezh said, what you have described for bandit is in fact what categorical is in GPyOpt. bandits are more complex (say in the example Javier mentioned they look extremely like categorical, but there is a notion of distance). Two others you got right.

They are something library was expected, but never needed to support, so at the moment they are not really used much and are probably incresing the confusion.

It may also be telling that in our new library emukit we chose not to have bandits altogether.

Finally, if these explanations helped your understanding, feel free to put together a PR for our docs, we'll be happy to merge.

**Comment by LarsHH** [comment]
Great! Thanks @javiergonzalezh and @apaleyes this helped! Closing the issue.
