### ISSUE TITLE
Question about the GP-LCB acquisition function

### ISSUE THREAD

**Issue by AnthonyLarroque** [SheffieldML/GPyOpt#240]
Dear GPyOpt developers,

First of all, thank you very much for the GPyOpt software.

I would have a question regarding the LCB acquisition function. 

In the LCB.py, I saw that you referred this acquisition function as the GP-LCB acquisition function. If I understand the program correctly, the exploration weight is set by default to the constant 2. However, in some articles that I saw (Brochu et al.,  arXiv:1012.2599, 2010 and  Srinivas et al., Proc. International Conference on Machine Learning (ICML), 2010), the GP-UCB (used for maximization purposes) is referred as an alternative acquisition function to the UCB (Upper Confidence Bound) whose the exploration weight depends on the number of function evaluations.

Thus, is the exploration weight constant all along the optimization when using AcquisitionLCB or does it change with the number of iterations ?

**Comment by javiergonzalezh** [comment]
Hi @AnthonyLarroque you are totally right! We keep that parameter constant for simplicity but in practice the right thing to do is to change it with the number of iterations. 

This may be hard to do in GPyOpt and if you want to do that what I recommend is to use [Emukit](https://amzn.github.io/emukit/) (that we also develop). In this framework, you can handle the number of iterations within the loop state, so it should be pretty easy to implement.

**Comment by AnthonyLarroque** [comment]
Hi @javiergonzalezh,

Thank you very much for your answer ! I will then take a look at this software.

Except for the LCB acquisition function, could you please, briefly describe me the main differences with GPyOpt ? Is there something more that Emukit can do but not GPyOpt ?

**Comment by apaleyes** [comment]
Emukit is much more general-purpose: it is not specializing in bayes opt, you can also do other active learning type of things there. It is also much more modular. Kind of what ModulareBayesOpt class in GPyOpt attempts to do, but in a easier to use way.

In general, if you'd like to implement your own element of bayes opt, say a new acquisition function, or plug a new model, it would be easier and more straightforward for you to do it in emukit than in gpyopt.

THat's the main difference we see between the two, and also why we shifted our focus on emukit

**Comment by AnthonyLarroque** [comment]
Thank you very much for your answer, it helps me a lot !

Regards,
Anthony Larroque

**Comment by apaleyes** [comment]
to round off this discussion i've updated the docsting in https://github.com/SheffieldML/GPyOpt/blob/master/GPyOpt/acquisitions/LCB.py to highlight constant weights and reference the paper

**Comment by rvvincelli** [comment]
Hi @apaleyes @AnthonyLarroque , as a coincidence I am also looking into this, good to start from your input. I see the `Acquisition` [base class](https://github.com/EmuKit/emukit/blob/master/emukit/core/acquisition/acquisition.py#L11) knows an `update_parameters` [method](https://github.com/EmuKit/emukit/blob/master/emukit/core/acquisition/acquisition.py#L69) and while it is parameterless the current iteration may be kept internally and incremented at each invocation. Or are there easier ways? I might give it a try.

**Comment by rvvincelli** [comment]
Something along these [lines](https://gist.github.com/rvvincelli/6e72ab554f03c35e093fdfb1048be34f) might work, I'll get feed on the project git, thanks,
