### ISSUE TITLE
Modular batch optimization?

### ISSUE THREAD

**Issue by fipeop** [SheffieldML/GPyOpt#242]
Hi guys!

Thanks for the awesome code.

I have a question, I need to run the modular Bayesian optimization, is batch Bayesian optimization working with that as well? I don't see a batch option in the modular model definition. 

Thanks,
Felipe.

**Comment by apaleyes** [comment]
Can you explain a bit what do you mean by "modular Bayesian optimization"? If it is the ModularBayesianOptimization class, then there are no options there. What is class does is it allows you to create all Bayes Opt components separately. One of them is the acquisition function, so you should be able to use local penalization acquisition with batch settings.

I will however point out that most GpyOpt users don't use ModularBayesianOptimization, so I am not fully aware of how stable it is. If you find it malfunctioning, feel free to create a PR, or check out emukit, our new library that is created around modular approach, and also has LP implemented

**Comment by fipeop** [comment]
Thanks, yes I meant the ModularBayesianOptimization class. I want to modify the acquisition function to include unknown constraints. 

Could you point me please to the acquisition function with local penalization and batch settings in GPyOpt? 

Emukit looks great, will definitely give it a try!

**Comment by apaleyes** [comment]
Here it is: https://github.com/SheffieldML/GPyOpt/blob/master/GPyOpt/acquisitions/LP.py

**Comment by fipeop** [comment]
Thank you!
