### ISSUE TITLE
Creating a new model resets old model

### ISSUE THREAD

**Issue by mhinne** [SheffieldML/GPyOpt#243]
When I create multiple GPRegression models, it appears as if the creation of a 2nd model resets the optimized parameters learned for the 1st. E.g.:

```
X = np.linspace(0, 1, num=50)
Y = 0.5 + 0.1*X + np.random.normal(50)

m1   = GPy.models.GPRegression(np.atleast_2d(X).T, np.atleast_2d(Y).T, kernel)   
m1.optimize()
print(m1)

m2   = GPy.models.GPRegression(np.atleast_2d(X).T, np.atleast_2d(Y).T, kernel)  
print(m1)
```
This prints
```
Name : GP regression
Objective : -386.2776637421206
Number of Parameters : 4
Number of Optimization Parameters : 4
Updates : True
Parameters:
  GP_regression.           |                   value  |  constraints  |  priors
  sum.Mat32.variance       |      113343.69344020663  |      +ve      |        
  sum.Mat32.lengthscale    |      12356.040079422111  |      +ve      |        
  sum.white.variance       |  5.562684646268137e-309  |      +ve      |        
  Gaussian_noise.variance  |  5.562684646268137e-309  |      +ve      |   
```

for the first print(m1) and 

```
Name : GP regression
Objective : -386.2776637421206
Number of Parameters : 1
Number of Optimization Parameters : 1
Updates : True
Parameters:
  GP_regression.           |                   value  |  constraints  |  priors
  Gaussian_noise.variance  |  5.562684646268137e-309  |      +ve      |        
```

for the second print(m1) (note that I am printing *m1* twice).

Is this intended behaviour? Is there a way I can de-link the two models so that I can work with their separately optimized hyperparameters?

**Comment by apaleyes** [comment]
Did you want to open this issue in https://github.com/SheffieldML/GPy ? Seems hardly related to GPyOpt.

You would need to create a new kernel object too. Yes, model and kernel objects are linked together so that their parameters can be optimized simultaneously, and there is no way to avoid this behavior - this is just how GPy works.

**Comment by mhinne** [comment]
Ah my apologies, that was indeed the wrong place :/ but thanks for solving the issue for me regardless!

**Comment by apaleyes** [comment]
no probs!
