### ISSUE TITLE
Local Penalization Wrong Implementation

### ISSUE THREAD

**Issue by LilyEvansHogwarts** [SheffieldML/GPyOpt#249]
@javiergonzalezh 
In paper **Batch Bayesian Optimization via Local Penalization**, the local penalization factor is:

![img](http://latex.codecogs.com/svg.latex?%5Cvarphi%28x%2Cx_j%29%3D%5Cfrac%7B1%7D%7B2%7Derfc%28-z%29), where ![img](http://latex.codecogs.com/svg.latex?z%3D%5Cfrac%7B1%7D%7B%5Csqrt%7B2%5Csigma%5E2_n%28x_j%29%7D%7D%28L%5C%7Cx-x_j%5C%7C-M%2B%5Cmu_n%28x_j%29%29), which equals to ![img](http://latex.codecogs.com/svg.latex?%5Cvarphi%28x%2Cx_j%29%3DCDF%28-%5Csqrt%7B2%7Dz%29).

However, the implementation of local penalization in file **LP.py** equals:
![img](http://latex.codecogs.com/svg.latex?log%28AcquisitionFunction%2ALP%29%3Dlog%28AcquisitionFunction%29-log%28CDF%28%5Csqrt%7B2%7Dz%29%29).

I think it should be changed to ![img](http://latex.codecogs.com/svg.latex?log%28AcquisitionFunction%2ALP%29%3Dlog%28AcquisitionFunction%29%2Blog%28CDF%28-%5Csqrt%7B2%7Dz%29%29).

And the **AcquisitionFunction._hammer_function** should be changed from:
```python
return norm.logcdf((np.sqrt((np.square(np.atleast_2d(x)[:,None,:]-np.atleast_2d(x0)[None,:,:])).sum(-1))- r_x0)/s_x0)
```
to:
```python
return norm.logcdf((r_x0 - np.sqrt((np.square(np.atleast_2d(x)[:,None,:]-np.atleast_2d(x0)[None,:,:])).sum(-1)))/s_x0)
```
There are also other issues talking about the inaccurate numerical results and gradients when it comes to local penalization.  I thinks this is the corresponding reason.
#205 #87

**Comment by apaleyes** [comment]
Hey! Thanks for the issue. Would you be able to implement these changes locally and let us know if this helped resolve the gradients issue?
