### ISSUE TITLE
Useless computation in evaluate_objective

### ISSUE THREAD

**Issue by forgi86** [SheffieldML/GPyOpt#250]
In function evaluate_objective, in GPyOpt.core.bo.py:   

 def evaluate_objective(self):
        """
        Evaluates the objective
        """
        self.Y_new, cost_new = self.objective.evaluate(self.suggested_sample)
        self.cost.update_cost_model(self.suggested_sample, cost_new)
        ......

I think the cost model should only be required when the cost for function evaluation is of type 'evaluation_time'. The function could be modified to:

if self.cost.cost_type == 'evaluation_time':
    self.cost.update_cost_model(self.suggested_sample, cost_new)

**Comment by apaleyes** [comment]
Hi, sorry for delay in response. Can you please elaborate why do you think this change is needed?

**Comment by forgi86** [comment]
Hello, sorry for the late response. 

I double-checked and indeed the same check is done inside update_cost_model, thus there is no need to implement the change I previously proposed.

Cheers,
Marco
