### ISSUE TITLE
Not able to import GPyOpt

### ISSUE THREAD

**Issue by squy999** [SheffieldML/GPyOpt#251]
Hi,
I have installed GPyOPT using pip, apparently with no problems as I got the following message:
“_Successfully installed GPy-1.9.8 gpyopt-1.2.5_”.
However, when I tried to import GpyOpt in a Jupyter notebook I got the following message:
 “_numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject_”

I have a python version 3.6.6 and a scipy version '0.18.1'
Could anyone figure out what the problem is?

Thanks

**Comment by apaleyes** [comment]
That appears to be numpy versioning issue. Check out this: https://github.com/scikit-image/scikit-image/issues/3655 . StackOverflow also has several threads about this error.
