### ISSUE TITLE
batch > 1 does not work for 'sequential'

### ISSUE THREAD

**Issue by danielrjiang** [SheffieldML/GPyOpt#253]
Hi, when I change the evaluator_type from 'local_penalization' to 'sequential', it seems that only one point is generated even if `batch_size = 4`. I tested this by simply looking at `myProblem.X` before and after `run_optimization` is called. Can anyone let me know if there is a bug? Thanks!
cc: @balandat

**Comment by apaleyes** [comment]
That's not a bug at all, in fact this is how sequential is designed to work, hence its name. It just completely ignores "batch_size" setting.

**Comment by Balandat** [comment]
So there is no support for sequential conditioning via "fantasizing"?

**Comment by apaleyes** [comment]
Emm, what's "sequential conditioning via "fantasizing""? I don't think I fully understand this phrase, although it does sound very fancy

**Comment by danielrjiang** [comment]
Thanks for the reply @apaleyes and for clarifying that is how it is supposed to work. Re: the "sequential conditioning", basically it is something along the lines of what is described at the bottom of page 6 here (https://papers.nips.cc/paper/8194-maximizing-acquisition-functions-for-bayesian-optimization.pdf), where we get the first point in the batch by maximizing EI, the second point in the batch by conditioning on "fantasy" observations of the first point drawn from the model, and so on ("sequential" optimization of the acquisition function, but before any new data is observed).

**Comment by apaleyes** [comment]
@danielrjiang i see. no, this is not supported, sequential is a simple one-by-one evaluator
