### ISSUE TITLE
Number of iterations to run to find optimum

### ISSUE THREAD

**Issue by aquibjamal** [SheffieldML/GPyOpt#259]
I am not sure, if I can add this as an issue here.

I am working on 3 models to find the optimum Hyper-parameters for them. The first model has 8 hyper-parameters each taking 5 different values. The second model has 19 hyper-parameters and third model has 38 hyper-parameters, all of them taking 5 different values. The resulting search space now in each case is 5⁸, 5¹⁹ and 5³⁸. With such huge search spaces, how many iterations of Bayesian optimization should I run in each model to be sure that optimizer has converged?
Currently I run 50 iterations of optimizer, but I am not convinced that the hyper-parameter set obtained after such small number of iterations is right.

Any specific value for number of iterations to run based on search space size?
I have also read that beyond 20 dimensions, Bayesian optimization is not efficient. So is it advisable to use Bayesian optimization with 38 hyper-parameters?

**Comment by apaleyes** [comment]
it sounds like your space is entirely discrete. gpyopt won't be of much help with it out of the box, and i am not sure any vanilla Bayes Opt method would. you may need to refer to literature for handling this case.

as for 20 iterations - that is very case dependent, there is no general rule that says bayes opt quality decreases beyond 20 iterations

**Comment by aquibjamal** [comment]
Thank you very much for your feedback !
