### ISSUE TITLE
Early stopping once objective function is below threshold

### ISSUE THREAD

**Issue by rshanker779** [SheffieldML/GPyOpt#261]
Hi, 
I would like to be able to exit early from the optimization if the error drops below a certain limit (so as soon as Y_new drop below some user inputted threshold function returns)- from looking at the BO object on master it doesn't look like this is currently supported. 

If this isn't currently supported this is a feature I could add to the code.

**Comment by apaleyes** [comment]
there is no such functionality in gpyopt. feel free to fork and add it, but we will have to see if we accept such a PR, as this use case seem pretty limited.

**Comment by rshanker779** [comment]
Actually on consideration I agree. I think the most general functionality would be something akin to callbacks as in scipy.optimize.minimize https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html - to support user defined functions that enable early termination. Is there any scope for a feature like this?

**Comment by apaleyes** [comment]
yes, that might be interesting to have, if customizable.

but if "in scope" you mean "are you planning to work on it" - the answer is no, we are focusing on our new framework Emukit, and gpyopt is mostly in maintenance mode these days. that is, we don't develop new features for gpyopt, and they are only coming as PRs. so if you are willing to work on it and submit a PR, we will consider it.

**Comment by rshanker779** [comment]
Ah ok, I didn't know about Emukit. Looking at it it's got the flexibility I need, so will port code over. I will close this issue, thanks
