### ISSUE TITLE
Question: Does Thompson Sampling not use the Acquisition Function?

### ISSUE THREAD

**Issue by LarsHH** [SheffieldML/GPyOpt#264]
Hi there,

I was wondering whether setting `evaluator_type='thompson_sampling'` uses the methodology  described e.g. here http://proceedings.mlr.press/v84/kandasamy18a/kandasamy18a.pdf and therefore doesn't make use of the acquisition function?

Thanks,
Lars

**Comment by apaleyes** [comment]
Thompson sampling currently in gpyopt has to do with optimization procedure (see https://github.com/SheffieldML/GPyOpt/blob/master/GPyOpt/optimization/acquisition_optimizer.py), not the kind of acquisition function the paper means.

So this parameter does not affect the acquisition function selection of usage, if that makes sense
