### ISSUE TITLE
Question: How can I access the history of x values/locations sampled while optimising?

### ISSUE THREAD

**Issue by stephan-jacobs** [SheffieldML/GPyOpt#267]
I'd like to make a visualisation of the path followed by the optimiser for both educational and investigative purposes. Essentially what I'd like to make is data that contains:
 * iteration number
 * X as a numpy array

I assume there's a way to do this but 2 hours hunting through the docs has produced little for me so far. Apologies if it's a silly/trivial question.

**Comment by apaleyes** [comment]
Of course! Let's say `bo = GPyOpt.methods.BayesianOptimization` is your optimizer, then use `bo.X` and `bo.Y` to find arrays of Xs and Ys seen so far. They are ordered accoring to the iteration. Also remember that if you've given `bo` some initial data, it will be inside these arrays too.

**Comment by stephan-jacobs** [comment]
Brilliant! Thanks for the help!
