### ISSUE TITLE
Custom constraints

### ISSUE THREAD

**Issue by mtezzele** [SheffieldML/GPyOpt#269]
Sorry for the possible duplication, I was not able to find an answer to the following question:
Is there a way to make use of other functions inside the constraints definition? Something like the following:

`constraints = [{'name': 'constr1', 'constraint': 'my_function(x[:])'}]`

I see that the `indicator_constraints` method see only `globals()` from within space.py...

Thank you in advance for the help. This is a great package!

**Comment by apaleyes** [comment]
Yes, your observation is correct. However, you may be able to pass your custom function by declaring it "global". Never tried it myself, but have a go at:
```
global my_function
def my_function(x):
     ....
```

Some more details about defining global functions: https://stackoverflow.com/q/27930038/728795

**Comment by mtezzele** [comment]
The problem is that the `globals()` dictionary of my file is different from the one that space.py has.

**Comment by apaleyes** [comment]
Oh, right. Well, i wasn't aware of other way to modify global namespace, so i guess honest reply is that your use case is not supported. Feel free to fork the library and expand the scope of constraints.

**Comment by mtezzele** [comment]
Thank you for the help!
