### ISSUE TITLE
Possible Inaccuracy in Bayesian Optimization

### ISSUE THREAD

**Issue by kwh5484** [SheffieldML/GPyOpt#274]
I noticed a possible issue with Bayesian Optimization in GPyOpt when using just a few points and doing incremental updates. It appears that the Gaussian Process is storing the correct (x, f(x)) points, but when plot_acquisition() is called the plotted points are inaccurate which affects how the acquisition function selects the next point. I've tested this on multiple machines using different acquisition functions and both the modularized/regular versions of BayesianOptimization(). I've included a simple test case in order to replicate the error. Any help would be appreciated!

```
from GPyOpt.methods import BayesianOptimization
import numpy as np
from numpy.random import seed
import matplotlib.pyplot as plt

seed(3)
def f(x): return -np.sin(x)
domain = [{'name': 'var_1', 'type': 'continuous', 'domain': (-3,3)}]

myBopt = BayesianOptimization(f=f, domain=domain, initial_design_numdata=1, exact_feval=True)

myBopt.run_optimization(0)
print('GP x vals: ', myBopt.X)
print('GP y vals: ', myBopt.Y)
myBopt.plot_acquisition()

myBopt.run_optimization(1)
print('GP x vals: ', myBopt.X)
print('GP y vals: ', myBopt.Y)
myBopt.plot_acquisition()

myBopt.run_optimization(1)
print('GP x vals: ', myBopt.X)
print('GP y vals: ', myBopt.Y)
myBopt.plot_acquisition()

myBopt.run_optimization(1)
print('GP x vals: ', myBopt.X)
print('GP y vals: ', myBopt.Y)
myBopt.plot_acquisition()

#for comparision
x = np.linspace(-3, 3, 100)
plt.plot(x, f(x))
plt.show()
```

**Comment by apaleyes** [comment]
I don't believe `run_optimization` was designed to support this use case. The way it is implemented assumes it will only be run once. That is, if you run it many times, each one is considered to be the first, without any memory of previous runs.

If you would like to do incremental updates, you would need to create new `BayesianOptimization` for each step. As example is here: https://github.com/SheffieldML/GPyOpt/blob/master/manual/GPyOpt_external_objective_evaluation.ipynb

**Comment by kwh5484** [comment]
Great, thanks!
