### ISSUE TITLE
Using new kernel (ODE_UY) without gradients_X() implemented `NotImplementedError`

### ISSUE THREAD

**Issue by ekalosak** [SheffieldML/GPyOpt#279]
I'm trying to use a different kernel with GPyOpt, but it appears that the acquisition optimizer requires calculating dK_dX.

Here is my code:
```
from GPyOpt.methods import BayesianOptimization
from GPy.kern import ODE_UY
import GPyOpt

def f(x): return (6*x-2)**2*np.sin(12*x-4)
domain = [{'name': 'var_1', 'type': 'continuous', 'domain': (0,1)}]
kernel = ODE_UY(input_dim=len(domain))
bo = BayesianOptimization(
    f=f,
    domain=domain,
    model_type='GP',
    kernel=kernel
    )
bo.run_optimization(max_iter=15, verbosity=True)
```

It produces a `NotImplementedError` - the tail of the traceback is:
```
File "/Users/eric/.pyenv/versions/venv-oco-3.6/lib/python3.6/site-packages/GPyOpt/acquisitions/base.py", line 46, in acquisition_function_withGradients
    f_acqu,df_acqu = self._compute_acq_withGradients(x)
  File "/Users/eric/.pyenv/versions/venv-oco-3.6/lib/python3.6/site-packages/GPyOpt/acquisitions/EI.py", line 47, in _compute_acq_withGradients
    m, s, dmdx, dsdx = self.model.predict_withGradients(x)
  File "/Users/eric/.pyenv/versions/venv-oco-3.6/lib/python3.6/site-packages/GPyOpt/models/gpmodel.py", line 136, in predict_withGradients
    dmdx, dvdx = self.model.predictive_gradients(X)
  File "/Users/eric/.pyenv/versions/venv-oco-3.6/lib/python3.6/site-packages/GPy/core/gp.py", line 434, in predictive_gradients
    self._predictive_variable)
  File "/Users/eric/.pyenv/versions/venv-oco-3.6/lib/python3.6/site-packages/GPy/kern/src/kernel_slice_operations.py", line 142, in wrap
    ret = s.handle_return_array(f(self, dL_dK, s.X, s.X2))
  File "/Users/eric/.pyenv/versions/venv-oco-3.6/lib/python3.6/site-packages/GPy/kern/src/kern.py", line 178, in gradients_X
    raise NotImplementedError
```

My hunch was that `gradients_X()` is required for optimizing the acquisition function using gradients, but using `model_type='GP_MCMC'` and `acquisition_type='EI_MCMC'` to avoid this gradient calculation changed nothing.

What am I missing?

**Comment by apaleyes** [comment]
yes, your hunch is correct. both EI and EI_MCMC require model to implement `predict_withGradients` method, which in turn expects (through a couple of nested calls) `gradients_X` method from the kernel.

to try and work this around you could create acq object yourself and set `analytical_gradient_prediction` to False. i think this will make gpyopt optimization to not call `predict_withGradients`. if you do that, please let us know how this went!

**Comment by ekalosak** [comment]
Thanks for the feedback - I'll try that method and report back with results.
In the meantime: why does EI_MCMC require analytical gradients for the acquisition function? I take it it's not doing direct sampling of the AcqFxn's domain - is there a brief explanation of its process, or is that something to be included in the "how to make new models" doc?

**Comment by ekalosak** [comment]
@apaleyes Turns out that simply implementing `gradients_X` and `gradients_X_diag` as:
```
    def gradients_X(self, dL_dK, X, X2=None):
        pass

    def gradients_X_diag(self, dL_dK, X, X2=None):
        pass
```
works. It does make for a slow acquisition optimization, but that follows intuitively: analytical gradients being unavailable forces the acquisition optimizer's L-BFGS-B implementation to calculate approximate gradients using finite difference methods. Supporting this narrative:

- https://github.com/scipy/scipy/blob/e53897db8416c0165b32883396023009d47cff22/scipy/optimize/optimize.py#L171
- https://github.com/SheffieldML/GPyOpt/blob/master/GPyOpt/optimization/optimizer.py#L36-L51

especially L49 in `GPyOpt/optimization/optimizer.py`. When profiled, this call stack spends most of its CPU time in the `2-point` finite difference scheme approximating the function's Jacobian in the L-BFGS-B acquisition optimizer.
I suspect this means, further, that `analytical_gradient_prediction` is not used when deciding whether to use the analytical gradient - whether gradients_X returns None or not, on the other hand, implicitly decides whether to use analytical gradients.
