### ISSUE TITLE
GP_MCMC and EI_MCMC and integrating hyperparameters

### ISSUE THREAD

**Issue by AliBaheri** [SheffieldML/GPyOpt#28]
Dear Javier!
I want to solve an optimization problem and "concurrently" optimize the hyperparameters of covariance function. In other words, we are interested to initialize the hyperparametes at very first step by some values, then improve them at each iteration. (there is some reason for this simultaneous goal). 
My question is does the GP_MCMC and EI_MCMC is fit for this goal? I see a notebook is available entitling "GPy_Opt_integrating_model_hyperparameters" however, I am not sure if that is similar to my case (sorry I am very new to this statistical machine learning concept).

Thanks for your help!

**Comment by javiergonzalezh** [comment]
Both, with MCMC and when you do MLE, the hyper-parameters of the model are updated after each iteration. Now, by setting ```save_models_parameters= True`` when running the optimisation you can also save the hyper-parameters of all the created models.

Hope this help!
