### ISSUE TITLE
Jupyter notebook tutorial link broken

### ISSUE THREAD

**Issue by ekalosak** [SheffieldML/GPyOpt#280]
The link to the "how to make a new model" tutorial is broken from the index page.

<img width="1045" alt="Screen Shot 2019-11-27 at 1 29 55 PM" src="https://user-images.githubusercontent.com/6068321/69760725-2113f780-111a-11ea-8fa4-b1ff119d2c0e.png">

**Comment by apaleyes** [comment]
thanks for pointing that out. feel free to cut a PR, we'll be happy to merge in the fix

**Comment by ekalosak** [comment]
One small hitch: there is no tutorial for creating a new models in the `manual/` subdirectory. When I have a solid process for doing so, I'll write up a brief ipynb - until then, I suggest removing the entire sentence. Thoughts?

**Comment by apaleyes** [comment]
oh, good call out. i've looked at commit history, and it turned out we had this notebook at some point, and the it got dropped.

notebook is back now, and the link works. thanks for spotting that!
