### ISSUE TITLE
Categorical variables not working with GP's

### ISSUE THREAD

**Issue by Rayn2402** [SheffieldML/GPyOpt#282]
When creating search space for my hyperparameters, one of them is categorical and goes like this:

{'name': 'var_1', 'type': 'categorical', 'domain':('a','b'), 'dimensionality':1}

which seems correct because of this line : 

supported_types = ['continuous', 'discrete', 'bandit','categorical'] in Space.py

However, when running the optimization I get the following error  

__ValueError : could not convert string to float: 'a'__

Is there any way to make it work? Thank you!

**Comment by apaleyes** [comment]
it is very unintuitive, but the way gpyopt handles categorical is that it takes in the range of indexes of categories. So what you should give it is

    {'name': 'var_1', 'type': 'categorical', 'domain':(0, 1), 'dimensionality':1}

Example can be seen in one of our tutorial notebooks: https://github.com/SheffieldML/GPyOpt/blob/master/manual/GPyOpt_mixed_domain.ipynb

Sorry about such a confusing api!

**Comment by Rayn2402** [comment]
Excellent! Thank you!
