### ISSUE TITLE
Using physical data, when plotted it looks like the fit is negative where it should be positive

### ISSUE THREAD

**Issue by will-colea** [SheffieldML/GPyOpt#288]
Hello, thank you in advance for your help. 

I am trying using physical data and predicting the next point I should run an experiment at using the bayesian optimization function from this package.

When I plot the acquisition function and the GP fit with the data, it plots negative values even though all of the data is positive. Do I need to constrain my fit somehow or am I feeding in my data incorrectly? Please let me know your thoughts.

`# --- Load matplotlib
import matplotlib

# --- Load GPyOpt
from GPyOpt.methods import BayesianOptimization
import numpy as np

X_step = np.array([[0],[16],[20],[24],[32],[80]])

Y_step = np.array([[0.81], [1.03], [1.02], [1.03], [0.62], [0.43]])

# --- Define your problem
domain = [{'name': 'var_1', 'type': 'continuous', 'domain': (0,100)}]

# --- Solve your problem
myBopt = BayesianOptimization(f=None, domain=domain, X = X_step, Y = Y_step)
x_next = myBopt.suggest_next_locations()

print(x_next)
myBopt.plot_acquisition()`

**Comment by ekalosak** [comment]
I can replicate, this is curious...
<img width="628" alt="Screen Shot 2020-01-13 at 2 22 57 PM" src="https://user-images.githubusercontent.com/6068321/72297203-413b3f80-3610-11ea-804c-8cecc30a9522.png">

**Comment by will-colea** [comment]
Yes, I do not know what is the issue. You can see how the y-axis aka the f(x) value does not actually match the data points. Do you know what could be the issue?

**Comment by ekalosak** [comment]
The default is `normalize_Y=True`. Setting it to false in `myBopt = BayesianOptimization(f=None, domain=domain, X = X_step, Y = Y_step, normalize_Y=False)` fixes the issue:
<img width="622" alt="Screen Shot 2020-01-13 at 4 44 06 PM" src="https://user-images.githubusercontent.com/6068321/72303995-017e5300-3624-11ea-918d-05f7abcbdc67.png">

**Comment by will-colea** [comment]
Hello @ekalosak - 

Thank you for your help and comments. I am actually trying to minimize, but I appreciate the input about the maximize option.  I will do some more digging into if I want to normalize the GP or not. If it is a better estimator with the normalization then I will leave it with the mean set to zero. I really appreciate your help and insight. Thanks again!
