### ISSUE TITLE
Advice on Visualizing Multivariate Optimization in GPyOpt

### ISSUE THREAD

**Issue by will-colea** [SheffieldML/GPyOpt#291]
Hello All -

Thank you in advance for your help and thank you for this great library! It is very useful. 

I am using GPyOpt to do Bayesian Optimization provided 3D data (eventually higher dimensional data as well) i.e. X1, X2, and X3. I am wondering if you have any advice on how to effectively visualize the results of the optimization. The plot_acquisition function is great for the 1D case, so I am wondering if there is a way I can extract the optimization results and take a 2D slice that I can then feed into the plot_acquisition function somehow. 

If you have any advice on how to achieve this or if you could refer me to example, I would really appreciate the help. Thank you in advance!

**Comment by ekalosak** [comment]
I like to use a pairs plot with the color proportional to the score on the lower triangular and the color proportional to the step number on the upper triangular.
You could also try a pairs plot with size proportional to step and score proportional to color - it's a taste thing.
I've also used animations (time = step, z = score, x = X1, y = X2) for projections onto X1 and X2, but it really depends on who you're presenting to - sometimes the glitz of an animation can distract from your message.

**Comment by will-colea** [comment]
Thank you @ekalosak.  I will definitely try these ideas!

**Comment by ekalosak** [comment]
<img width="541" alt="Screen Shot 2020-02-06 at 7 36 15 PM" src="https://user-images.githubusercontent.com/6068321/74064554-c283b900-49a7-11ea-8c0f-8d88c5950b7f.png">
e.g. the diagonal is just the marginal frequencies of values used on each dimension, the lower diagonal is a 2D marginal of the ibid - just using 2D marginals rather than 1D marginals - and the upper diagonal colors the score and uses size for step number.

**Comment by lawrennd** [comment]
This is nice, is there someway of adding the code to create it e.g. as a gist somewhere?

**Comment by ekalosak** [comment]
@lawrennd that modified pairs-plot is written in R, for better or worse. I can turn around a gist pretty quickly (pending an internal review here at Opsani) if there're no concerns about bleeding the codebase into another language.

**Comment by lawrennd** [comment]
No worries if it's too much trouble, but it would be cool to see it somewhere!

**Comment by ekalosak** [comment]
@lawrennd here's the gist: https://gist.github.com/ekalosak/f2582f7420374d394ab10d2dda056aaa
