### ISSUE TITLE
Difference between 2 ways of Bayesian Optimization

### ISSUE THREAD

**Issue by tqa236** [SheffieldML/GPyOpt#292]
Hello, I would like to know what is the difference between these 2:

```
GPyOpt.methods.BayesianOptimization
```

Source: https://github.com/SheffieldML/GPyOpt/blob/master/manual/GPyOpt_modular_bayesian_optimization.ipynb 

and 

```
GPyOpt.methods.bayesian_optimization.BayesianOptimization
```

Source: https://gpyopt.readthedocs.io/en/latest/GPyOpt.methods.html

It seems to me that they're the same but I'm not sure about that. In case they are really the same, which one do you recommend to use?

**Comment by apaleyes** [comment]
Exact same class, just imported in two different ways. `BayesianOptimization` is a class defined in `GPyOpt.methods.bayesian_optimization` package. But we also have `__init__.py` file inside `GPyOpt.methods` that imports this class, kind of lifting up one level. Have a look: https://github.com/SheffieldML/GPyOpt/blob/master/GPyOpt/methods/__init__.py

So in the end you can use both ways and end up with exactly same class.

**Comment by tqa236** [comment]
Thank you very much for the quick response. I will close the issue.
