### ISSUE TITLE
plot_acquisition() plots the wrong y-values

### ISSUE THREAD

**Issue by tawe141** [SheffieldML/GPyOpt#295]
Hi,

I have a fairly complex function that should always return a number >=0. Print statements in this function indicate this is satisfied. Running `opt.fx_opt` gives a value close to 0, which should be the true minimum. However, `opt.plot_acquisition` shows negative numbers at the minimum. This shouldn't be an artifact of the underlying gaussian process model, as even the points in red where GPyOpt evaluates the function is negative. Why is this the case?

![acquisition](https://user-images.githubusercontent.com/13124532/73681507-79242880-468c-11ea-9560-0c81ed2b7513.png)

**Comment by apaleyes** [comment]
Can you share the code that produced that plot? There might be few reasons for this behavior. Have you normalized y, for instance?

**Comment by javiergonzalezh** [comment]
Outputs in GPyOpt are normalized by default, which makes the optimization
of the acquisition easier. Could this be the problem?

**Comment by ekalosak** [comment]
re: @javiergonzalezh 's comment, this issue has popped up before: https://github.com/SheffieldML/GPyOpt/issues/288
Should we consider setting normalization to false initially? Seems to trip people up regularly, we might apply principal of least surprise and then lay out the (debatable) necessity of output normalization in the tutorials.

**Comment by tawe141** [comment]
Yep, looks like `plot_acquisition()` was normalizing Y, making it seem weird. I'm not sure setting it to false by default is the best option if the optimization performs better with normalized values. Perhaps it could be documented somewhere?

**Comment by ekalosak** [comment]
If you find it helpful, please augment the docs (and make a PR!) with what you think makes most sense to someone who is encountering this issue for the first time - your perspective there would be especially helpful.

And close the issue :)

**Comment by apaleyes** [comment]
@ekalosak we could stop normalizing outputs by default, but slight worry though is that those who already use GPyOpt might be taken by surprise with this new behavior

**Comment by ekalosak** [comment]
@apaleyes Is there a list of such breaking changes for a next major version?

**Comment by tawe141** [comment]
Maybe it would be appropriate to normalize internally, then un-normalize when plotting?
