### ISSUE TITLE
ImportError: No module named 'core'

### ISSUE THREAD

**Issue by stmax82** [SheffieldML/GPyOpt#3]
I tried to run the first example from the manual:
http://nbviewer.ipython.org/github/SheffieldML/GPyOpt/blob/master/manual/GPyOpt_reference_manual.ipynb

The line:

```python
import GPyOpt
```

fails with the following error:

```
ImportError: No module named 'core'
```

Happens on Python 3.4 / Windows 8 x64.

I think the problem is Python 3.x, but I cannot use another version because of other packages... any way to fix this?

**Comment by javiergonzalezh** [comment]
Hi stmax82,

we have't done the shift of GPyOpt to Python 3.X as we did with GPy but
this will happen in the upcoming weeks.

I will keep you posted.

Javier

**Comment by glouppe** [comment]
Hi! +1 on this, I hit the same the issue

**Comment by lawrennd** [comment]
Hmm @javiergonzalezh where are you with this one? @glouppe is mentioning on
twitter he'd be interested in helping, I'm sure you'd be very happy with
that!! I'm sure @mikecroucher would also be happy to provide some informal
advice (when he's recovered from his flu!).

**Comment by javiergonzalezh** [comment]
We were planning to address this directly with with the release of the level branch. Because it may take a few weeks to have it fully ready, let me check with @mikecroucher what we can do with the master.   @glouppe, any help is welcome!

**Comment by mikecroucher** [comment]
I'm almost 100% recovered from flu and itching to get this project converted to Python 3.5. I assume that you'd like it done in such a way that it also runs on Python 2 as a first pass.

**Comment by glouppe** [comment]
@javiergonzalezh I can work on that, while of course maintaining Python 2 compatibility. As a scikit-learn developer, I have experience with that :) Unless @mikecroucher you prefer tackling that yourself?

**Comment by mikecroucher** [comment]
@glouppe Ideally, I'd like to tackle it together. I think we all have a lot to learn from someone of your experience

**Comment by javiergonzalezh** [comment]
That's great guys, thanks a lot. The devel version has a number of new bits and quite a lot code restructuring but it is not fully usable yet (code runs but I need to write some wrappers and tests). Shall we first for the master then?

**Comment by mikecroucher** [comment]
Sure, lets play.

**Comment by glouppe** [comment]
Okay then, I'll start branching off the master branch and work within my own repo. @mikecroucher I'll give you write access over there so that we can work together. Does it work for you?

**Comment by mikecroucher** [comment]
sounds great!

**Comment by lawrennd** [comment]
Great work all!
