### ISSUE TITLE
Small fix

### ISSUE THREAD

**Issue by Paul1298** [SheffieldML/GPyOpt#300]
https://github.com/SheffieldML/GPyOpt/blob/33d207ea4ace75cc9437750093e6970b07e79a39/GPyOpt/methods/bayesian_optimization.py#L28

Need add **task** to 
`See GPyOpt.core` **.task** `.space.Design_space class for details.`
And below the same changes

**Comment by ekalosak** [comment]
Please make a small PR :D

**Comment by ekalosak** [comment]
Please consider implementing these changes in a fork, then making a PR from that fork. Happy to help if it's not clear how to do this!

**Comment by Paul1298** [comment]
[Done](https://github.com/SheffieldML/GPyOpt/pull/305)
