### ISSUE TITLE
Inconsistency in default values and inner

### ISSUE THREAD

**Issue by Paul1298** [SheffieldML/GPyOpt#301]
In https://github.com/SheffieldML/GPyOpt/blob/master/GPyOpt/core/bo.py#L73
`max_iter = 0, max_time = np.inf`

But in https://github.com/SheffieldML/GPyOpt/blob/master/GPyOpt/core/bo.py#L107
`max_iter` and `max_time` compared with `None`

**Comment by apaleyes** [comment]
Hey @Paul1298. I believe second chunk of code should be read as: "if user has set these fields to `None`, this is invalid, reset them to default values". So it is there to cover cases when users accidentally did something explicit like `max_iter=None`.

Whether this is a good design is a different question, but at least i see no contradiction. Does it make things clear?

**Comment by Paul1298** [comment]
@ekalosak yes, thank you!
