### ISSUE TITLE
Can I pass the Y known to the Bayesian Optimization as the initial setting?

### ISSUE THREAD

**Issue by WuSht** [SheffieldML/GPyOpt#303]
Hello,
Thanks for so powerful software! Recently, I used it to search neural networks' hyper-parameter which is a time-consuming procedure. Sometimes my program ran out of memory and crashed.
So, I have some known independent variable X with their dependent variable Y of my neural network function. Can I pass them into GPyOpt as the initial known variables which prevents calculating those variables once more.

Regards,
Wu Shiauthie

**Comment by ekalosak** [comment]
Usually, you'll want your neural net hyperparameters to be the X input to the Bayesian optimizer and your test set accuracy of the trained network to be the Y output of the objective function. For example, see the following pseudocode:
```
train, test = split(training_data)
def obj_f(hyperparameters):
  nn = train_my_neural_net(train, hyperparameters)  # takes a long time
  score = test_neural_net(nn, test)
  return(score)
bo = BayesianOptimization(objective=obj_f, space=...)
best_param=bo.run_optimization()
print(f"Yay! Your net performed best using hyperparameters: {best_param}")
```

The details of your question are slightly unclear - you might consider posting code, or even pseudo-code, to help guide the discussion.

**Comment by WuSht** [comment]
Thank you for replying to my question.
Actually, my question is that,
The X input of the optimizer is the neural net hyperparameters
`bounds = [
          #Discrete 
          {'name':'sp_drop','type':'discrete','domain':(0.1, 0.2, 0.3, 0.4)},
          {'name':'kernel_rate','type':'discrete','domain':(0.3, 0.4, 0.5, 0.6, 0.7)},
          {'name':'fn_drop','type':'discrete','domain':(0.1, 0.2, 0.3, 0.4)},
          {'name':'batch_num', 'type': 'discrete','domain': (128, 256, 512)},
          {'name':'layer_num', 'type': 'discrete','domain': (2, 3)},
          {'name':'em_dim', 'type': 'discrete','domain': (10, 12, 14, 16, 18)},
          {'name':'kernel_num', 'type': 'discrete','domain': (1, 1.2, 1.4)},
          #Categorical
          {'name':'opti', 'type': 'categorical','domain': (0, 1, 2)}
         ]`
and the function in the optimizer is
`def search_param(x):
    opt= DotMap()
    opt.sp_drop = float(x[:, 0])
    opt.kernel_rate = float(x[:, 1])
    opt.fn_drop = float(x[:, 2])
    opt.batch_num = float(x[:, 3])
    opt.layer_num = int(x[:, 4])
    opt.em_dim = int(x[:, 5]) 
    opt.kernel_num =int(x[:, 6])

    opt.opti = int(x[:,7])
    return opt

def f(x):
    
    opt = search_param(x)

    param = {'sp_drop':opt.sp_drop,
           'kernel_rate':opt.kernel_rate,
           'fn_drop':opt.fn_drop,
           'batch_num':opt.batch_num,
           'layer_num':opt.layer_num,
           'em_dim':opt.em_dim,
           'kernel_num':opt.kernel_num, 

           'opti':opt.opti}

model = main(**param)        # this is the neural net function
    y_test_pred = model.predict([x_test_1,x_test_2])
    evaluation = mean_squared_error(y_test, y_test_pred)

    with open('search_log.txt', 'a') as log:
        log.write('evaluation: ' + str(evaluation) + '\n')
        log.write('---------\n')

    print('cycle: ' + str(yy))
    print('evaluation: ' + str(evaluation))

    return evaluation`
We can see the f(x) function takes hyperparameters as the X input, and mean_squared_error as Y output.
Then, I run the optimizer
`opt_model = GPyOpt.methods.BayesianOptimization(f=f, domain=bounds, initial_design_numdata=10)
opt_model.run_optimization(max_iter=30)`

**Comment by WuSht** [comment]
```
bounds = [{'name':'sp_drop','type':'discrete','domain':(0.1, 0.2, 0.3, 0.4)},{'name':'kernel_rate','type':'discrete','domain':(0.3, 0.4, 0.5, 0.6, 0.7)},{'name':'fn_drop','type':'discrete','domain':(0.1, 0.2, 0.3, 0.4)},
{'name':'batch_num', 'type': 'discrete','domain': (128, 256, 512)},
{'name':'layer_num', 'type': 'discrete','domain': (2, 3)},
{'name':'em_dim', 'type': 'discrete','domain': (10, 12, 14, 16, 18)},
{'name':'kernel_num', 'type': 'discrete','domain': (1, 1.2, 1.4)},
{'name':'opti', 'type': 'categorical','domain': (0, 1, 2)}]

```

**Comment by apaleyes** [comment]
Your code currently instructs GPyOpt to generate some initial data before kicking off optimization. With this parameter: `initial_design_numdata`

Now if instead of passing this you pass the values of X and Y you already have, with `X=exist_x, Y=exist_Y`, gpyopt will use that as initial data, and won't generate any more random points. Caveat: Y is expected to be 2d array.

**Comment by WuSht** [comment]
Thank you very much! Now, I have known how to deal with those data and the correct format of Y.

**Comment by ekalosak** [comment]
@WuSht please close the issue and consider adding your learning to the Wiki :D
