### ISSUE TITLE
Release on PyPi is 2+ years old

### ISSUE THREAD

**Issue by ekalosak** [SheffieldML/GPyOpt#307]
https://pypi.org/project/GPyOpt/1.2.5/
What's the process to cut a new release?

**Comment by zhenwendai** [comment]
There is no regular release schedule but we can push the release out if there are sufficient changes. Any blocking changes that you want to update PyPi with shortly?

BTW: I am working on some relatively big changes at the moment and may cut a release soon.

**Comment by ekalosak** [comment]
Perhaps cut a 1.2.6 release with what exists here (2+ years of bugfixes and feature additions) and a 1.3 with your big changes?

**Comment by lawrennd** [comment]
Sounds a good strategy (just tagging also @apaleyes @javiergonzalezh)

**Comment by javiergonzalezh** [comment]
That sounds good to me too! Starting next week, I will be able to have a
look to CRs before merging (if you think that is needed) and to start
contributing again.

We probably need to sync a bit the developments here and in Emukit so we
avoid doing the same thing twice. Right now, we have feature parity (in
terms of the basic components) and new stuff is way easier to implement in
Emukit. What we don’t have in Emukit though is an big BayesianOptimzation
wrapper that allows to run BayesOpt in a couple of lines with some smart
default options.

A way forward could be to work on a future GPyOpt release ‘powered’ by
Emukit so we keep Emukit as the place for new components and research and
GPyOpt2 as the place for well stabilised wrappers with key parameters
(ideally integrated with Pandas, etc). Two examples of use cases:

- I want to do autoML in a scikit-learn model and I am not an expert in
AutoML-BayesOpt: I use the GPyOpt.
- I want to develop and benchmark an new BayesOpt/BQ/AL method: I use
Emukit.

Eventually we’ll stabilised recipes can be wrapped and ‘promoted’ from
Emukit to GPyOpt. We actually have a spot for that in Emukit but I think
that the GPyOpt brand is stronger for this use case.

Just an idea! Comments are welcome.

**Comment by zhenwendai** [comment]
The version 1.2.6 is released now.

**Comment by ekalosak** [comment]
Thank you - it might be a bit much to ask, but it would be great to have the commit tagged here in GitHub as a release commit with the associated notes. @zhenwendai

**Comment by zhenwendai** [comment]
Do you know any automatic ways to do that?

> Thank you - it might be a bit much to ask, but it would be great to have the commit tagged here in GitHub as a release commit with the associated notes. @zhenwendai

**Comment by ekalosak** [comment]
It's basically like doing a `git commit -m "here's a summary of what's changed"` - there's nothing to automate (or, it requires strong AI to automate) on top of CI. You just have to click "release" and write a small release summary.

Here's the 123 for how to tag a release on GitHub - it's a 5m process on top of writing the release notes: https://help.github.com/en/enterprise/2.16/user/github/administering-a-repository/creating-releases

**Comment by zhenwendai** [comment]
From what I understand, you suggest to have a changelog and a release tag. It is doable.

**Comment by ekalosak** [comment]
Closing - @zhenwendai thank you for fixing!
