### ISSUE TITLE
How to pass in constraints as functions

### ISSUE THREAD

**Issue by cmleecm** [SheffieldML/GPyOpt#322]
The current way of specifying the constraint explicitly on the variables x_1, ..., x_n doesn't quite work for me because the constraint I am working with is itself another black box. Therefore I will need to pass in the constraints as functions e.g.

constraints = [{'name': 'constr_1', 'constraint': f_1},
                      {'name': 'constr_2', 'constraint': f_2}]

Is it possible to do this in GPyOpt?

**Comment by apaleyes** [comment]
Unfortunately no, this is not supported. A bit more discussion in #285

**Comment by cmleecm** [comment]
Thanks for the quick response. Looking forward to the addition of this feature.
