### ISSUE TITLE
what is email distribution list or other way of communication for GPyOpt?

### ISSUE THREAD

**Issue by pavel-rev** [SheffieldML/GPyOpt#323]
On U of Sheffield's website the distribution list is mentioned but the link is broken.

**Comment by lawrennd** [comment]
I think we've mainly moved to using the issues now. Do you have a location where that link is? we should probably take it down.

**Comment by pavel-rev** [comment]
it is here: http://sheffieldml.github.io/GPyOpt/forum/index.html
it says "mailing list" with a link to https://lists.shef.ac.uk/sympa/info/gpyopt-users
when I press it, it says: "ERROR () - gpyopt-users : unknown list | ERROR (info) - Wrong parameters". And I search in "list of lists" - no such list exists.

**Comment by apaleyes** [comment]
The link is now removed. Please use GitHub Issues going forward. Thanks!
