### ISSUE TITLE
pre-computed search space

### ISSUE THREAD

**Issue by pavel-rev** [SheffieldML/GPyOpt#324]
I forked this project and did some modifications to pre-computed search space for the case of discrete variables with constraints. What is the process to get green light for this changes to be merged to master (i.e. pull request approval process)?

**Comment by lawrennd** [comment]
Normal pull request submission, e.g. you can see it in operation here: https://github.com/SheffieldML/GPyOpt/pull/320

**Comment by pavel-rev** [comment]
Let me share my use case again here: It is expensive to run objective function (let's call it a numerical simulation run). Variables (~10, 30 in number in worst cases) are mostly discrete, with the same search space (Di in 0 to 100% with 5% step), with constraints imposed (variable values should monotonically decline, i.e. Di>=Di+1). We are in concept phase. I did a little research on existing packages for Bayesian Optimization with GPs and GPyOpt looks good. I already made one basic test run, and it showed good results. The initial parameter space setup took "infinite" time to pick proper anchor points, so I passed a pre-computed search space directly to sample from (we assume all search space will be available in most cases, at least part of it in worst case scenarios). For now i have own cloned repo on premises, but i was suggested that I submit a pull request through GitHub to this open source project to simplify future maintenance. Now I am asking how feasible is such custom feature to be merged to master.

**Comment by ekalosak** [comment]
Sounds like you want to provide your own initial experiment design?

That's 100% possible and doesn't necessarily require dev work - using the ModularBayesianOptimization setup when small custom modifications are required has been a successful strategy for using custom initial designs.

And for all this, we should still address the elephant in the room of why it took a long time to produce an initial design for you 🤔

**Comment by pavel-rev** [comment]
something like initial experiment design.

now I am using step by step evaluation as I need to wait for my objective function to compute.

    bo_step = GPyOpt.methods.BayesianOptimization(f=black_box_function,
                                                  domain=domain,
                                                  constraints=constraints,
                                                  all_x_values=all_x_values,
                                                  X=X,
                                                  Y=Y,
                                                  maximize=maximize,
                                                  normalize_Y=True,
                                                  de_duplication=True,
                                                  initial_design_type="random")

**Comment by apaleyes** [comment]
@pavel-rev as an example of using ModularBO class, see this notebook: https://nbviewer.jupyter.org/github/SheffieldML/GPyOpt/blob/master/manual/GPyOpt_modular_bayesian_optimization.ipynb

as you can see, it takes array of initial points, and obviously this can be produced by any means including your custom code

**Comment by pavel-rev** [comment]
the problem I am having is in initial design for anchor points in acquisition optimization. in this example by initial design X_init, Y_init is meant.

**Comment by pavel-rev** [comment]
currently I am trying to replace acquisition function optimizer in modular setting.

**Comment by pavel-rev** [comment]
GPyOpt.optimization.acquisition_optimizer you have random_design_type = "random" as constant - pain to modify that. you should consider redesigning that.

**Comment by ekalosak** [comment]
@pavel-rev Might I gently suggest you revise your etiquette on this thread? Many times, in software development, communication and personal skills are more important than technical prowess. This Medium post (specifically point 6) is a great place to start: https://medium.com/@teejeetech/etiquette-in-open-source-projects-f302b6e19c38

**Comment by pavel-rev** [comment]
I had to monkey patch some parts for now and everything works fine. sorry, guys, it was just a suggestion.

**Comment by ekalosak** [comment]
I think I just misread what you wrote pavel-rev - my bad if I've overstepped!!
Anyway, this code snippet looks good - why not make a PR?

**Comment by pavel-rev** [comment]
I am going to work on this PR soon, please do NOT close the issue in the meantime.

**Comment by pavel-rev** [comment]
NB: this is bug, not a feature, as described here: https://github.com/SheffieldML/GPyOpt/pull/343

**Comment by pavel-rev** [comment]
btw: example of constraints I get issues with performance in anchor points generator for acquisition function optimization:
```
    D = X_ALL.shape[1] # D = 63
    unique_values = tuple([round(e, 2) for e in sorted(np.unique(X_ALL), reverse=False)])
    space = [{'name': 'var_0',
              'type': 'discrete',
              'domain': unique_values,
              'dimensionality': D}]

    # # d_n <= d_n-1 -> d_n - d_n-1 <= 0
    constraints = [{'name': 'const_' + str(i),
                    'constraint': "x[:, " + str(i+1) + "] - x[:, " + str(i) + "]"}
                   for i in range(0, D-1)]
```

**Comment by pavel-rev** [comment]
I created test case reproducing the bug:
[test to reproduced bug in anchor points generator](https://github.com/pavel-rev/GPyOpt/blob/issue-324_precomputed_search_space_modular_option/GPyOpt/gpyopt_mod/tst_bo_bug.py)
