### ISSUE TITLE
Issue with Scipy 1.5.0+

### ISSUE THREAD

**Issue by sherpa-ai** [SheffieldML/GPyOpt#329]
Hi! We are using GPyOpt as a dependency. It looks like the Scipy optimize API has changed which [causes an exception when used with GPyOpt](https://github.com/sherpa-ai/sherpa/issues/98). Just wanted to make you aware of this. Using version 1.4.1 seems to work.
Best,
Lars

**Comment by apaleyes** [comment]
the fix is merged, thanks @zhenwendai !
