### ISSUE TITLE
The way to change from minimize to maximize

### ISSUE THREAD

**Issue by snpc94** [SheffieldML/GPyOpt#33]
Nice to meet you.
I belong to a university in Japan.(e,g. I'm a Japanese and a university student)

These days I use GPyOpt to research Bayesian Optimization.
To learn about GPyOpt, I read this .
http://nbviewer.jupyter.org/github/SheffieldML/GPyOpt/blob/devel/manual/GPyOpt_reference_manual.ipynb
There is a example how to solve "minimize" problem.
But there is not a example how to solve "maximize" problem.
Could you teach me how to change problem from "minimize" to "maximize" by using GPyOpt's function or tool?

I'm sorry I can't explain my problem well for my poor vocabulary.
And I little have knowledge GPyOpt and BaysianOptimization,so I'll be glad to teach answer simply.  
Thank you in advance for your help.

**Comment by javiergonzalezh** [comment]
To maximize you just need to pass the negative of your function. The location where *f(x)* has its minimum is the same as the location where *-f(x)* has its maximum.
Hope it helps! and thanks for using GPyOpt!

**Comment by snpc94** [comment]
Thank you for your quick reply.
I'll try to this way and make effort to grow up my ability about GPyOpt and BayesianOptimization!
