### ISSUE TITLE
Multi objective optimization

### ISSUE THREAD

**Issue by CuriousSingularity** [SheffieldML/GPyOpt#338]
Hello, may I know whether the GPyOpt supports multi objective functionality? If so, could you please direct me to an example program. 
Thank you.

**Comment by ekalosak** [comment]
You might check out amzn/emukit - it's the "successor" to GPyOpt (same devs, more or less, with a more flexible, modern framework.)
There's a tutorial for MF BO there: https://nbviewer.jupyter.org/github/amzn/emukit/blob/master/notebooks/Emukit-tutorial-multi-fidelity.ipynb

**Comment by CuriousSingularity** [comment]
Great. Thanks for the tip. I will check it out.
