### ISSUE TITLE
`f0` passed has more than 1 dimension.

### ISSUE THREAD

**Issue by MarvinStuede** [SheffieldML/GPyOpt#341]
Python Version: 3.7.6
GPyOpt Version: 1.2.6

Hey everyone,

while trying out the [GPyOpt_parallel_optimization.ipynb](https://github.com/SheffieldML/GPyOpt/blob/master/manual/GPyOpt_parallel_optimization.ipynb) notebook I run into the error 

```
~/venv/lib/python3.7/site-packages/scipy/optimize/_numdiff.py in approx_derivative(fun, x0, method, rel_step, abs_step, f0, bounds, sparsity, as_linear_operator, args, kwargs)
    386         f0 = np.atleast_1d(f0)
    387         if f0.ndim > 1:
--> 388             raise ValueError("`f0` passed has more than 1 dimension.")
    389 
    390     if np.any((x0 < lb) | (x0 > ub)):

ValueError: `f0` passed has more than 1 dimension.
```

The error does only occur for 'local_penalization' as evaluator type, the other methods seem to work fine.

**Comment by apaleyes** [comment]
Hi! Accidentally we have encountered this issue in a different package. See https://github.com/amzn/emukit/issues/316 for details. Td;lr: donwgrade scipy to 1.4.1 and it should do it.
