### ISSUE TITLE
Is there any example for spatiotemporal Gaussian process?

### ISSUE THREAD

**Issue by Ethanwl** [SheffieldML/GPyOpt#348]
I want to model a dynamic objective function as a spatiotemporal Gaussian process. How can I implement it? Is there any example for spatiotemporal Gaussian process?

**Comment by apaleyes** [comment]
I think this question is better addressed to GPy repo, which is a modelling lib GPyOpt relies on. As far as GPyOpt goes, you are able to provide a custom model to it, our API allows that.

Here is an example of GPy used for similar purpose: https://github.com/SheffieldML/notebook/blob/master/GPy/Space_time_effects.ipynb
