### ISSUE TITLE
How to check lengthscales when ARD=True.

### ISSUE THREAD

**Issue by ktakihara2000** [SheffieldML/GPyOpt#360]
I do Bayesian optimisation in two dimensions.
When 'ARD' is set to 'True', printing kernel outputs '(2, )'.
I would like to check the respective lengthscale in 2D, is there a way to do this?

**Comment by ekalosak** [comment]
Can you post your code example? I think I understand what you're trying to accomplish, it will be easier to help when you post real code.

**Comment by ktakihara2000** [comment]
@ekalosak 
Does this make sense to you?
I am new to github so I am not used to it. Apologies.


`kern = GPy.kern.RBF(input_dim=2, variance=0.3, lengthscale=1, ARD=True)`
`print(kern)`
`params = {param1, param2, ----}`
`myBopt = GPyOpt.methods.BayesianOptimization(**params)`
`print(kern)`
------------------------------------------------------------------------------------
  rbf.         |  value  |  constraints  |  priors
  variance     |    0.3  |      +ve      |        
  lengthscale  |   (2,)  |      +ve      |   

rbf.         |              value  |  constraints  |  priors
  variance     |  23.72151391342812  |      +ve      |        
  lengthscale  |               (2,)  |      +ve      |

**Comment by ekalosak** [comment]
I'd recommend two sources to help in learning Bayesian Optimization implementations on Python:
1. The GPyOpt tutorials
2. Emukit and its tutorials
I have a hunch that, if you can replicate the results in the relevant tutorials, your problem above might resolve.

@lawrennd please close the issue, this is not a problem with the code.

**Comment by apaleyes** [comment]
thanks @ekalosak !
