### ISSUE TITLE
_update_model with one data point

### ISSUE THREAD

**Issue by davek44** [SheffieldML/GPyOpt#37]
In line 194 of GPyOpt/core/bo.py
`self.model.updateModel(self.X,(self.Y-self.Y.mean())/(self.Y.std()),self.suggested_sample,self.Y_new)`

You might want to check for self.Y having >1 data points to work with. I was just doing a single random run (i.e. initial_design_numdata=1) before trying to call run_optimization, and it crashes without any error message on that line because the standard deviation is 0.

**Comment by javiergonzalezh** [comment]
You are totally right. Thanks for that! It is corrected now!
