### ISSUE TITLE
save_models_parameters for GPModel_MCMC

### ISSUE THREAD

**Issue by davek44** [SheffieldML/GPyOpt#38]
In line 64 of GPyOpt/core/bo.py,
`if not isinstance(self.model, GPyOpt.models.GPModel) or isinstance(self.model, GPyOpt.models.GPModel_MCMC):`

Based on the subsequent error message, I'm guessing it should be,
`if not (isinstance(self.model, GPyOpt.models.GPModel) or isinstance(self.model, GPyOpt.models.GPModel_MCMC)):`

**Comment by javiergonzalezh** [comment]
Good point! It is corrected now.
