### ISSUE TITLE
Optimizer: Trying to use CMA results in crash

### ISSUE THREAD

**Issue by jprk** [SheffieldML/GPyOpt#39]
When porting from the old-style code, the `Opt_CMA` class seems to have lost its `optimize()` method -- in fact, the code is there, but it is a part of `__init__()`. As a result, when trying the CMA acquisition optimizer, the default `Optimizer::optimize()` is used which returns a pair of `None`'s ...

I have it fixed and running (actually the test will finish some time tommorrow) together with some other fixes to `optimize.py`. Shall I create a pull request?

**Comment by javiergonzalezh** [comment]
Sorry for the slow response. I have been on holidays. Yes, just make a pull request and we will integrate that out.

Thanks for contributing!

**Comment by javiergonzalezh** [comment]
There are two problems here. 
1- CMA does not work in examples of dimension 1 (not sure if this is your case though).
2 - When the optimizers are called, actually it is done in a way suitable for lbfgs but not general enough to cover other gradient-free cases. I am doing some work on this to improve the implementation of this bit.

**Comment by ab07** [comment]
I have the same issue using acquisition_optimizer_type='CMA'.  I get the warning message "CMA does not work in examples of dimension 1" even though my objective function is on a 7 dimensional domain. Has this been fixed already?

**Comment by javiergonzalezh** [comment]
This is a problem of the CMA optimizer, not of GPyOpt. CMA does not work in problems of dimension one, so you need to select another optimizer here.

**Comment by a-z-e-r-i-l-a** [comment]
> This is a problem of the CMA optimizer, not of GPyOpt. CMA does not work in problems of dimension one, so you need to select another optimizer here.

I have also used it for a six dimensional problem but the same error shows up.
