### ISSUE TITLE
Discrete and categorical data?

### ISSUE THREAD

**Issue by CarrKnight** [SheffieldML/GPyOpt#4]
Can GPyOpt currently deal with categorical and discrete inputs? I couldn't find any tutorial on this aspect

**Comment by javiergonzalezh** [comment]
Hi CarrKnight
Still it is not possible to deal with discrete inputs but that is something we have in mind to implement. Soon, we will have ready a module for bandits optimization in the devel brach.
Javier

**Comment by CarrKnight** [comment]
Cheers, thanks!

**Comment by javiergonzalezh** [comment]
Back again! Have a look to the notebook in the devel branch

https://github.com/SheffieldML/GPyOpt/blob/devel/manual/GPyOpt_mixed_domain.ipynb

We have tested it some examples and it seems to work well but we are still testing it.

**Comment by CarrKnight** [comment]
this was perfect, thank you!

**Comment by 1Reinier** [comment]
Are discrete variables also fitted with a GP? Or are they assumed to be categorical / having no local correlation?

**Comment by ekalosak** [comment]
@1Reinier This depends on the choice of kernel, no? I'm interested in the anyone's take on implementing custom kernels on mixed type domains (e.g. [Zhou et al. 2011](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.165.2093&rep=rep1&type=pdf))

**Comment by matthew-hsr** [comment]
@ekalosak 

Could you elaborate more? What are the commonly used kernels? What are the advantages and disadvantages of each of them? Is there somewhere to read more about them? Thanks in advance!
