### ISSUE TITLE
Periodic Boundary Conditions in BO.model

### ISSUE THREAD

**Issue by milicasan** [SheffieldML/GPyOpt#41]
Dear Developers,
The model functions we seek to optimise with BO are known to have periodic boundary conditions (PBC), and introducing this feature into the model has previously saved us excessive sampling at the boundaries. We are now working with a simple RBF kernel in our BO.model, should we switch to the periodic-exponential to introduce PBC?
Many thanks, Milica.

**Comment by javiergonzalezh** [comment]
Could you give an example of one of the functions you are trying to optimize?

Javier

**Comment by milicasan** [comment]
Javi,
Almost all of our functions are periodic by definition, and the periods can vary. See examples below up to 2D with different lengthscales. In many of these cases, we need only sample the original period, this increases the density of sampling and requires fewer acquisitions (which are expensive for us), see 1D examples. We can proceed without periodicity, but in 2D already this requires many more acquisition points as the code samples the opposing boundaries when sampling only one would do. All examples are BO with PBC from Michael's code based on gpml (no MCMC).
Best, Milica.

![1d_d7](https://cloud.githubusercontent.com/assets/19856648/16945683/b1e9d226-4dae-11e6-8ef6-ba6cc5b2e025.png)

![1d_gamma](https://cloud.githubusercontent.com/assets/19856648/16945695/b8a665b6-4dae-11e6-85a9-60134585f1d5.png)

![2d_d13-d4](https://cloud.githubusercontent.com/assets/19856648/16945860/962c9036-4daf-11e6-9336-8aa04593415d.png)

**Comment by snorlax** [comment]
Hi,

I work with Milica and I tried to switch our RBF kernel to
`GPy.kern.PeriodicExponential(input_dim=1, variance=250., lengthscale=60., period=2.*np.pi, n_freq=10, lower=0., upper=(360/180)*np.pi, active_dims=None, name='periodic_exponential')`
With RBF everything worked fine, but using PeriodicExponential results in a NotImplementedError:
`File "/u/53/paulamh1/unix/packages/newest/GPy/GPy/core/gp.py", line 331, in predictive_gradients
    mean_jac[:,:,i] = kern.gradients_X(self.posterior.woodbury_vector[:,i:i+1].T, Xnew, self._predictive_variable)
  File "/u/53/paulamh1/unix/packages/newest/GPy/GPy/kern/src/kernel_slice_operations.py", line 117, in wrap
    ret = s.handle_return_array(f(self, dL_dK, s.X, s.X2))
  File "/u/53/paulamh1/unix/packages/newest/GPy/GPy/kern/src/kern.py", line 132, in gradients_X
    raise NotImplementedError`
Are we doing something wrong to get this or is it meant to be working yet at all?
Thanks in advance :)

Best, Henri Paulamäki

**Comment by mzwiessele** [comment]
The gradients in X are not implemented for this particular kernel. If you want to give it a go, you can put the gradients in and push a pull request to GPy, we are always happy for contributions from the community :)

Have a look at the gradients in this, or use this kernel, which has the gradients_x implemented:

https://github.com/SheffieldML/GPy/blob/devel/GPy/kern/src/standard_periodic.py

Now I am not sure if that resolves the problem, but it is sure worth a try.

**Comment by javiergonzalezh** [comment]
In case it helps, in this tutorial you can also check how to write kernels
for GPy using theano.

http://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/theano_day/kernels_in_GPy.ipynb
