### ISSUE TITLE
Customising Bayesian Optimisation class

### ISSUE THREAD

**Issue by milicasan** [SheffieldML/GPyOpt#42]
Dear Developers,
Following the notebook tutorials, we started using the BayesianOptimisation class, but we soon found it restricted to particular option choices. In order to go custom, we switched to the core.BO class, which appears to be at the heart of modularBO. Is this the right way to go?
Best regards, Milica.

**Comment by javiergonzalezh** [comment]
You don't need to do that. You can do Bayesian optimization in a modular way where you can customize the different elements involved on it (acquisition, model, optimizer, etc). Have a look to this notebook:

https://github.com/SheffieldML/GPyOpt/blob/master/manual/GPyOpt_modular_bayesian_optimization.ipynb

**Comment by milicasan** [comment]
Hello Javier,
Thanks for your help on this one! We switched to the modular class, and it has made our life easier :+1: 
Best, Milica.

**Comment by javiergonzalezh** [comment]
Perfect!
