### ISSUE TITLE
Imaging updated model with each acquisition point

### ISSUE THREAD

**Issue by milicasan** [SheffieldML/GPyOpt#43]
Dear Developers,
When we run_optimisation, we cannot seem to image how the model evolves with each acquisition, we only see the end result. We found a notebook where the BO is run in a loop with max_iter=1; this of course illustrates the evolution of the model, but is the loop numerically equivalent to doing continuous BO (i.e. are the hyperparameters re-initialised with max_iter=1)? Ideally we would run BO continuously for max_iter=N steps, how would we plot at each step? 
Many thanks, Milica.

**Comment by javiergonzalezh** [comment]
Note that when you do the optimization 

```
def run_optimization(self, max_iter = 0, max_time = np.inf, eps = 1e-8, verbosity=True, save_models_parameters= True, report_file = None, evaluations_file= None, models_file=None):
```
you can choose the name of the file where you want to save the parameters of your model (models_file) and all the evaluations (evaluations_file). You could use those files to re-create the models at each evaluation. Alternatively you may need to create a wrapper over runs with ```max_iter=1```. The parameters are re-initialised but when multiple initialisations  are done the fist one is set to the previous value of the parameters.

**Comment by milicasan** [comment]
Hi Javier,
Thanks for explaining this point. We now understand that running the loop with max_iter=1 is equivalent to running the full cycle. We have found the regular hyperparameter output really useful, and now that we know the code better, we figured out how to output the model and plot at each step without having to do the loop.
All the best, Milica.

**Comment by javiergonzalezh** [comment]
Great it worked!
