### ISSUE TITLE
Acquisition optimizer error

### ISSUE THREAD

**Issue by 1Reinier** [SheffieldML/GPyOpt#45]
Hi,

I have been running into this error with both the DIRECT and CMA optimizers:

``` python-traceback
    133     if isinstance(s, np.ndarray):
    134         s[s<1e-10] = 1e-10
--> 135     elif s< 1e-10:
    136         s = 1e-10
    137     u = (fmin-m+acquisition_par)/s
```

Any idea how this is caused? I can't seem to figure out what `s` is and why it is a list.

**Comment by javiergonzalezh** [comment]
s is the standard deviation of the GP at the point you are looking at. That is a way of dealing with cases in which s is zero. Can you provide a example of the core you are trying to run so I can have a look to want is causing the error? 
And sorry for the slow response!

**Comment by 1Reinier** [comment]
This is still an issue for me
