### ISSUE TITLE
initial_design_numdata ignored when X, Y are set

### ISSUE THREAD

**Issue by sdrobert** [SheffieldML/GPyOpt#46]
Hi there,

First off: great job devs. This is a really nice package.

Second, if I initialize a `GPyOpt.methods.BayesianOptimization` object with some initial data points using args `X` and `Y`, but I also set `initial_design_numdata` to a positive value, it seems like the optimizer should still sample the latter number of points randomly _and_ fit the values from `X` and `Y`, rather than simply ignoring `initial_design_numdata`. Consider the following:
-  `initial_design_numdata` currently defaults to `None`. This seems like a value that might specify "no initial points if `X` and `Y` are set, otherwise use some constant value." If the behaviour is to always ignore `initial_design_numdata` in the face of `X` and `Y`, it might as well default to that constant value (5) straight away.
- Given that it is highly likely that the objective function takes a long time to calculate, it's a real possibility that initial sampling could have been cut short then restarted. As it stands, there's no way to resume random sampling if there are too few samples to build a half-decent initial model from. Concretely, I have sampled 2 points randomly which happen to be close together and I get underflow errors if I try initializing the model with just those two points.

Thanks very much for your time,
Sean

**Comment by javiergonzalezh** [comment]
This has been fixed in the new pre-release (still in devel). Have a look to it and let us know if you still have the issue.
