### ISSUE TITLE
problems when following firstexamples.md

### ISSUE THREAD

**Issue by andreh7** [SheffieldML/GPyOpt#51]
Thanks for making this library available to the public !

While trying to getting started with it, I tried to follow firstexamples.md and I noticed:
- `from GPyOpt import BayesianOptimization` does not work but `from GPyOpt.methods import BayesianOptimization` does
- my python interpreter does not like the backslash in `def f(x): return (6*x-2)**2\np.sin(12*x-4)`. Should it be `*` instead of `\` ?

(I installed GPyOpy and Gpy using pip on OSX, GPyOpt.**version** is 1.0.2 and GPy.**version** is 1.4.0 -- am I using a too old version or should firstexamples.md be updated ?)

**Comment by dunatotatos** [comment]
Thank you ! I was struggling with this example.

**Comment by javiergonzalezh** [comment]
ups! that's right! Corrected now!
