### ISSUE TITLE
Noiseless MPI assigns probability 1. to lowest sampled point.

### ISSUE THREAD

**Issue by rasmusbergpalm** [SheffieldML/GPyOpt#52]
I think there's a bug in the MPI acquisition function, as it assigns probability 1.0 to the lowest sampled point. See image:
![hmm](https://cloud.githubusercontent.com/assets/206013/18312490/4fc5c4be-750a-11e6-8847-c19915df10e4.png)

The green line is GPyOpt's MPI acquisition function and the blue is when I write down the equations myself. See https://gist.github.com/rasmusbergpalm/f73afd5bfed241b23d2cae33630ec41f for code that reproduces the above image. 

Since the model is noiseless I would think the probability of being lower with a non-zero margin (psi) should be 0.0

I think the problem is simply that psi is added rather than subtracted here https://github.com/SheffieldML/GPyOpt/blob/master/GPyOpt/util/general.py#L137. If i set psi to a negative value in the linked gist the image is reversed, i.e. GPyOpt gives the prob 0.0 and my equations prob 1.0

Best, Rasmus.

**Comment by javiergonzalezh** [comment]
Thanks so much for pointing this out. You are right that there should be a negative value there. I will do the merge.
Javier
