### ISSUE TITLE
Dimension bug in acquisition_optimizer

### ISSUE THREAD

**Issue by zhang8473** [SheffieldML/GPyOpt#57]
In GPyOpt_parallel_optimization.ipynb, I changed the var_1 from continuous to discrete and got the following error.

It seems there is an dimension bug somewhere.

I am using numpy==1.11.0, and latest GPyOpt release.

* This is my setup (the only thing that I've changed):
`domain = [{'name': 'var_1', 'type': 'discrete', 'domain': (-3,-2,0,1,2,3,4,5,6,7,8,10)},
{'name': 'var_2', 'type': 'continuous', 'domain': bounds[1]}]`

* This is the error message:
`GPyOpt/optimization/acquisition_optimizer.py, line 120, in fix_dimensions
    self.samples = self.samples[:,np.array(self.free_dims)] # take only the component of active dims
IndexError: index 1 is out of bounds for axis 1 with size 1`

**Comment by javiergonzalezh** [comment]
Yap, we are fixing this but. It happens that you need to have the continuous variables first and later the discrete ones. The optimization is carried out correctly in this case but it is a pain from the user perspective. We will have this fixed in the upcoming days.

Javier

**Comment by zhang8473** [comment]
I followed your instruction and now I have the continuous variables first and later the discrete ones.

However, the instance creation method prints lots of junk messages, which does not happen when I set all variables to "continuous".

<pre>
hyper_parameters_opt = GPyOpt.methods.BayesianOptimization(f = model.test_hyperpara,                  
                                          domain = model.hyper_parameters_domain,
                                          normalize_Y= True,
                                          exact_feval = True,
                                          model_type= 'GP',
                                          acquisition_type ='EI',       
                                          acquisition_jitter = 0.25)
</pre>

Junks printed. It also happens in run_optimization() method. How to turn it off?

<pre>
0
[1]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
-------------------------------
1
[1]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
-------------------------------
2
[1]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
-------------------------------
3
[1]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
-------------------------------
4
[1]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
-------------------------------
5
[1]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
-------------------------------
6
[1]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
-------------------------------
7
[1]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
-------------------------------
</pre>

**Comment by zhang8473** [comment]
I dug a little bit and found out the following:
You may use logger instead of print(), otherwise the users cannot turn it off. It slows down the process because those printing takes time.
<pre>
GPyOpt/optimization/acquisition_optimizer.py:            print(i)
GPyOpt/optimization/acquisition_optimizer.py:            print(self.discrete_dims)
GPyOpt/optimization/acquisition_optimizer.py:            print(self.discrete_values)
GPyOpt/optimization/acquisition_optimizer.py:            print("-------------------------------")
</pre>

**Comment by javiergonzalezh** [comment]
Hi Zhang,

This issue has been fixed in the devel branch. 

Javier
