### ISSUE TITLE
Error in parallel computation

### ISSUE THREAD

**Issue by zhang8473** [SheffieldML/GPyOpt#60]
As long as I setup batch_size>1, the model cannot even be built. I am looking for argmin(Y) of a XGBoost Model.

What is the problem?

Works:
<pre>
batch_size = 1
num_cores = 4

</pre>
Does NOT Work:
<pre>
batch_size = 3
num_cores = 1
</pre>

Model building:
<pre>
opt = GPyOpt.methods.BayesianOptimization(f = model.f,  
                                          domain = domain_norm,                  
                                          normalize_Y = True,
                                          model_type= 'GP',
                                          evaluator_type = 'local_penalization',
                                          batch_size = batch_size,
                                          num_cores = num_cores,
                                          acquisition_type = 'EI',              
                                          acquisition_jitter = 0.25) 
</pre>

When `batch_size>1`, model building hangs there forever, when I force to break it down, the error shows up:
<pre>
Error in parallel computation. Fall back to single process!
</pre>

**Comment by javiergonzalezh** [comment]
Hi,

Thanks a lot for the interests on GPyOpt! @zhenwendai can you have a look to this one?

Javier

**Comment by zhang8473** [comment]
I actually know the root cause. It is because you use Python multiprocess and the XGBoost use the multiprocess as well. However, Python does not allow you to launch multiprocess under multiprocess. Thus it will not work, but your package should automatically go back to the single process and finish the job.

**Comment by javiergonzalezh** [comment]
Thank for the comment. We are having a look to different ways of improving the parallelization. If you know how to address the problem and are willing to open a pull request on this we'd really your contributions on this!

Javier

**Comment by javiergonzalezh** [comment]
I close this one as @zhang8473 found the problem and @1Reiner has a follow up in issue #65.
