### ISSUE TITLE
Never-ending, non-stationary problems

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [SheffieldML/GPyOpt#62]
What is the recommended way of handling long-running (perhaps never-ending) non-stationary problems? 

E.g. Say we have a true objective function that varies over time in an unknown manner, with no end in sight. 

What is the recommended way of using GPyOpt in these types of problems? If the functionality to properly handle these types of problems isn't there yet (I don't know if that's the case), what heuristics/ tricks could work well for them?

**Comment by javiergonzalezh** [comment]
Hi,

In the current implemented methods you assume that the objective doesn't change after each evaluation. If it does, you need a way to updating your model accordingly. Here you have a reference of a bandits method that can handle that:

https://arxiv.org/pdf/1601.06650v1.pdf

If you are willing to implement it in GPyOpt I can give you some advice on how to do that!

Javier

**Comment by amelio-vazquez-reina** [comment]
Thank you @javiergonzalezh Very helpful. I have been going through the code slowly trying to understand all classes and methods and which function does what and why. I should be in good shape to dig deeper here soon.

**Comment by javiergonzalezh** [comment]
Great! Thanks for the interests!
