### ISSUE TITLE
More bugs with all discrete values

### ISSUE THREAD

**Issue by zhang8473** [SheffieldML/GPyOpt#63]
For example, I set domain = {["type":"discrete", "domain":(0,1)]}

Now the freedom of the parameter space is only 2. If I set max_iter =3, the GpyBayesianOptimizer will crash after two iterations, saying that it covers the entire parameter space.

However, that's limited the use cases. If the entire para-space has been covered, you should return the best rather than just crush....

**Comment by javiergonzalezh** [comment]
We have done some work on this that has been pushed to the devel branch. This problems should be fixed now. And thanks for mentioning it and using the library!
