### ISSUE TITLE
Batches with local penalization (Python 3)

### ISSUE THREAD

**Issue by 1Reinier** [SheffieldML/GPyOpt#65]
(Possibly related to #58 and #60.)

Hi there,

I've been having a lot of success implementing GPyOpt successfully for my application. Thanks for all the good stuff! 

I'd now like to speed things up by running batches with local penalization, as is implemented in the package. However, somehow any batch size larger than 1 will make my execution stall. Looking at my Activity Monitor, no python process will consume any CPU time anymore form that point onwards. After KeyboardInterrupting the process it will revert to sequential, non-parellel execution but that kind of takes away the point. Since I wrote my optimizable function from scratch I'm sure I am not employing any multiprocessing in my own code.

Do you have any advice on how to proceed or how I could adjust GPyOpt's code to make it work? I'm willing to contribute this adjustment to the Github if you give me a pointer where to look.

Thanks for your help!
Kind regards,

-Reinier

**Comment by javiergonzalezh** [comment]
Hi Reiner, 

Thanks for your interests in GPyOpt! In the main function there is an option to select the number of cores that you want to use. Have you tried to use that? Ideally you want to select the number of cores to be the same to the size of the batch, but it doesn't need to be necessarily the case.

Check if that works, and if not, we have try to see a bit more in detail what's the problem.

Javier
