### ISSUE TITLE
Why run_optimization ends in 5 steps even when max_iteration is set as 100?

### ISSUE THREAD

**Issue by yxchng** [SheffieldML/GPyOpt#68]
Why run_optimization ends in 5 steps even when max_iteration is set as 100?

**Comment by javiergonzalezh** [comment]
Hi!
That should be because one of the other stopping conditions is satisfied. I guess that in your problem you have started to collect samples that are very close and the distance between that last two evaluations is smaller than the eps default value.

Javier

**Comment by yxchng** [comment]
Is there a way make it keeps running? I make eps=0 but it doesnt work too

**Comment by javiergonzalezh** [comment]
The problem you have (I guess) is that the optimization converged. What I'd recommend is to increase the exploration in your search so you can escape from the local minimum.
Javier

**Comment by lawrennd** [comment]
Shouldn't setting eps to zero make it run quite long though?

It might indicate a trivial solution or a problem (perhaps in the system
you're trying to optimise)

**Comment by javiergonzalezh** [comment]
Indeed, seting it to zero should work. Another solution is to increase a
bit the exploration of the aquisition so it can jump from the potential
local minimum.
