### ISSUE TITLE
Is there an easy way to resume an optimization?

### ISSUE THREAD

**Issue by sellitforcache** [SheffieldML/GPyOpt#71]
Hi,

I'm using a very expensive objective function that is running on a cluster with a [not large] maximum run time.  Is there an easy way to re-enter evaluations (~100 or so) from a past run and resume to the optimization process?

Thanks,

Ryan

**Comment by javiergonzalezh** [comment]
Hi Ryan, 

you just need to run the .run_optimization(n_iter) again for the number of the iterations you want to resume it and it will start from the previous model/datasets.

Javier
