### ISSUE TITLE
How to get the prediction after run run_optimization

### ISSUE THREAD

**Issue by HairongG** [SheffieldML/GPyOpt#73]
Hi,

I am a new user of GPyOPT. I want to ask how to get the numerical prediction after a GP model is updated. In the 1D example on your website as follows, how can I obtain the prediction of a vector of X specified by me?

Thanks for your time.

# --- Load GPyOpt
from GPyOpt.methods import BayesianOptimization
import numpy as np

# --- Define your problem
def f(x): return (6*x-2)**2*np.sin(12*x-4)
bounds = [(0,1)]

# --- Solve your problem
myBopt = BayesianOptimization(f=f, bounds=bounds)
myBopt.run_optimization(max_iter=15)
myBopt.plot_acquisition()

**Comment by javiergonzalezh** [comment]
Hi,

To get the prediction of the model at x (a numpy array of inputs) you would need to do:
myBopt.model.model.predict(x)

Hope this helps!

Javier

**Comment by HairongG** [comment]
Thank you for the reply. That helps.
