### ISSUE TITLE
Math about EI Acquisition

### ISSUE THREAD

**Issue by Ivan-wang** [SheffieldML/GPyOpt#74]
Hi all, I really appreciate this framework. But I have a small question about the gradient of EI acquisition.

Since we have `f_acqu = (fmin - m + self.jitter) * Phi + s * phi` (use the same variables as the code), I think the gradient should be `df_acqu = -dmdx * Phi + (fmin - m + self.jitter) * dPhidx + dsdx * phi + s * dphidx` (also use the same variables as the code, and `dPhidx`, `dphidx`are the gradients of CDF and PDF).

Are we missing some factors by calculating `dsdx * phi - Phi * dmdx` in the code?

**Comment by Ivan-wang** [comment]
Oh, I think I have an explanation.. `dPhidx = dPhidu * dudx, dphidx = dphidu * dudx` in which `u = (fmin - m) / s`. And `dudx` is the gradient of `u`. Do we consider them  "negligible"?

**Comment by javiergonzalezh** [comment]
Hi Ivan,

terms cancel out since you are taking the gradients with respect to x and m and s also depend on x. It is funny the gradient of the EI looks so simple though!

Javier
