### ISSUE TITLE
Error when using a GPModel with optimize_restarts=1

### ISSUE THREAD

**Issue by nrontsis** [SheffieldML/GPyOpt#77]
Assume the following minimal example (with `GPy==1.6.1`, `GPyOpt==1.0.3`)

```python
import GPyOpt as GPyOpt

model = GPyOpt.models.gpmodel.GPModel(optimize_restarts=1)

obj = GPyOpt.objective_examples.experiments2d.branin()
bounds = obj.bounds
domain = [{'name': 'var_1', 'type': 'continuous', 'domain': bounds[0]},
          {'name': 'var_2', 'type': 'continuous', 'domain': bounds[1]}]

BO = GPyOpt.methods.BayesianOptimization(f=obj.f, model=model, domain=domain)
```

It produces the following error
```python
__init__() got an unexpected keyword argument 'verbose'
```
originating from [this](https://github.com/SheffieldML/GPyOpt/blob/master/GPyOpt/models/gpmodel.py#L87) line.

I suppose verbosity is only used to display the result of each optimization restart, and as such it is unnecessary when `optimize_restarts=1`.

**Comment by nrontsis** [comment]
Do you have any guidelines for contributing pull requests? :)

**Comment by Ivan-wang** [comment]
Hi, I also have this problem. And I found that  `verbose` is deprecated in GPy. So just change the argument name and it can work.

**Comment by javiergonzalezh** [comment]
This works now in the new pre-release (still in the devel branch)
