### ISSUE TITLE
Error in ContAcqOptimizer when fast=false

### ISSUE THREAD

**Issue by nrontsis** [SheffieldML/GPyOpt#78]
The following error occurs when trying to use `ContAcqOptimizer` with `fast=False`
```
TypeError: 'int' object is not iterable
```

It occurs from the following [line](https://github.com/SheffieldML/GPyOpt/blob/cf2c689319a4587b00c36fab9bb5bfc6c671cd47/GPyOpt/optimization/acquisition_optimizer.py#L185)
```python
for i in self.samples.shape[0]:
```
I believe that it should be changed to:
```python
for i in range(0, self.samples.shape[0]):
```

**Comment by javiergonzalezh** [comment]
you are right! Thanks a lot for pointing that out. Can you make a pull request?

Javier

**Comment by nrontsis** [comment]
Sure :)
