### ISSUE TITLE
Broken link - Tutorial Notebook

### ISSUE THREAD

**Issue by nrontsis** [SheffieldML/GPyOpt#8]
Hi,

The [link](http://nbviewer.jupyter.org/github/SheffieldML/GPyOpt/blob/master/manual/index.ipynb) for the Tutorial Notebook in the [README.md](https://github.com/SheffieldML/GPyOpt/blob/master/README.md) file is broken (the same link exists in manual/Readme.md and [here](https://github.com/SheffieldML/GPyOpt/blob/gh-pages/_layouts/home.html#L55)).

Maybe it should be changed to [this](http://nbviewer.jupyter.org/github/SheffieldML/GPyOpt/blob/master/manual/GPyOpt_reference_manual.ipynb) one?

Cheers!

Nikitas

**Comment by javiergonzalezh** [comment]
Changed! Thanks for mentioning it!
