### ISSUE TITLE
How to initiate a GPyOpt if I do not know the functional form

### ISSUE THREAD

**Issue by HairongG** [SheffieldML/GPyOpt#81]
Hi, many examples that presented in your reference manual such as the one below requires the knowledge of the true model for optimization. But in practice, we do not usually know the true model. What we experimenters obtain is just raw observations. So my question is how to make GPyOpt work without specifying a parametric model. More specifically, if what I have on hand is only the pairs of designs and observations (x1, y1, x2, y2, x3, y3,...), how GPyOpt is set up to work?

This is the example from your manual. In the example, the true model 'myf' needs to be entered in the function BayesianOptimization. Can you give an example without specifying myf? Thank you.
 
def myf(x):
    return (2*x)**2
bounds = [{'name': 'var_1', 'type': 'continuous', 'domain': (-1,1)}]

max_iter = 15
myProblem = GPyOpt.methods.BayesianOptimization(myf,bounds)
myProblem.run_optimization(max_iter)

**Comment by javiergonzalezh** [comment]
Hi,

You'd need a small wrapper for that. When you initialize the model with some observations the next location (next experiment) is automatically computed (`.suggested_sample`). This means that you don't actually need to run the optimization, just collect that point and run your experiments with it. Once you got more samples, you can simply pass the updated data set to  the model and recompute again.

Hope this help.

Javier

**Comment by apaleyes** [comment]
Hi @HairongG 

We have recently implemented an API for the library that allows you to do external objective evaluations. In this case you do not need a functional form, in fact it may not exist, all you need is to be able to provide an observation result at the point suggested by the GPyOpt.

You can find an example here: http://nbviewer.jupyter.org/github/SheffieldML/GPyOpt/blob/master/manual/GPyOpt_external_objective_evaluation.ipynb
