### ISSUE TITLE
Index Error in acquisition_optimizer.py: bug or problem?

### ISSUE THREAD

**Issue by akash13singh** [SheffieldML/GPyOpt#82]
Hi 

I am not sure if this is a bug or error in my usage. I am trying to optimize a RNN with only 3 hyperparameters, all discrete. I have included the code and the stacktrace. 

Please help me fix the error/bug.

**Code:**
```
from numpy.random import seed
import matplotlib
matplotlib.use('Agg')
#import matplotlib.pyplot as plt
import esr_multistep_lstm
import config as cfg
import logging
import GPyOpt

FORMAT = '%(asctime)-15s. %(message)s'
logger = logging.getLogger(__name__).addHandler(logging.StreamHandler())
logger = logging.basicConfig(filename=cfg.opt_config['log_file'], level=logging.INFO, format=FORMAT)

seed(123)
mixed_domain =[{'name': 'dropout', 'type': 'discrete', 'domain': (0.1,0.7,.1)},
               {'name': 'optimizer_index', 'type': 'discrete', 'domain': (0,2,1)},
               {'name': 'batch_size', 'type': 'discrete', 'domain': (256,1024,256)}]

myBopt = GPyOpt.methods.BayesianOptimization(esr_multistep_lstm.optimize_objective_function,                
                                             domain=mixed_domain,       
                                             initial_design_numdata = 3,
                                             acquisition_type='EI',     
                                             exact_feval = True)        
max_iter = 40
myBopt.run_optimization(max_iter) #error occurs here
logging.info(myBopt.X)
logging.info("==Optimum Hyperparams==")
logging.info(myBopt.x_opt)
```
The _esr_multistep_lstm.optimize_objective_function()_ returns the RMSE value. 

**Stacktrace**:
```
Traceback (most recent call last):
  File "bayes_opt.py", line 29, in <module>
    myBopt.run_optimization(max_iter)
  File "/opt/GPyOpt/GPyOpt/methods/bayesian_optimization.py", line 458, in run_optimization
    super(BayesianOptimization, self).run_optimization(max_iter = max_iter, max_time = max_time,  eps = eps, verbosity=verbosity, save_models_parameters = save_models_parameters, report_file = report_file, evaluations_file= evaluations_file, models_file=models_file)
  File "/opt/GPyOpt/GPyOpt/core/bo.py", line 108, in run_optimization
    self.suggested_sample = self._compute_next_evaluations()
  File "/opt/GPyOpt/GPyOpt/core/bo.py", line 186, in _compute_next_evaluations
    return self.evaluator.compute_batch() 
  File "/opt/GPyOpt/GPyOpt/core/evaluators/sequential.py", line 21, in compute_batch
    return self.acquisition.optimize()
  File "/opt/GPyOpt/GPyOpt/acquisitions/base.py", line 59, in optimize
    out = self.optimizer.optimize(f=self.acquisition_function, f_df=self.acquisition_function_withGradients)[0]
  File "/opt/GPyOpt/GPyOpt/optimization/acquisition_optimizer.py", line 230, in optimize
    while any((self.pulled_arms[:]==arms[index[k],:].flatten()).all(1)):
IndexError: index 27 is out of bounds for axis 0 with size 27
```

**Comment by akash13singh** [comment]
I found out that my setup was wrong. I misunderstood the domain of a discrete parameter to be a python range like function with step size ( e.g. for batch_size 'domain': (256,1024,256). So my setup required 43 evaluations of the objective function while the search space had only 8 points. The correct way to setup discrete variables is to explicitly specify all possible values i.e  'domain':(256,512,768,1024). Please correct me if I am wrong.

However I still got the same issue when my search space had 27 points and the max iterations was set to be 15. The error occurred after 13 evaluations. Maybe the search space was still not large enough to ask for 15 evaluations. I am still investigating and will update if I find anything else.

**Comment by javiergonzalezh** [comment]
Hi Akash,

You are right in the way you need to define your domain: you need to explicitly include all possible values. 

Regarding your second problem, I suspect that what is happening is that the methods wants two collect to points in the same location. In continuous sets, this triggers the stoping condition (epsilon < XX) but here you want to keep exploring. Just set epsilon to a negative or zero with running the optimization. That should work.

Cheers!

Javier

**Comment by akash13singh** [comment]
Thanks Javier for the answer. I understand the problem. I will close the issue for now.
