### ISSUE TITLE
What approach is used for Bayesian Optimization in GPyOpt?

### ISSUE THREAD

**Issue by iaroslav-ai** [SheffieldML/GPyOpt#9]
Did you build this code based on some specific paper / papers? If so, which ones?

**Comment by javiergonzalezh** [comment]
The reference paper we have used is:

https://papers.nips.cc/paper/4522-practical-bayesian-optimization-of-machine-learning-algorithms.pdf

but we have added some bits form other works. For instance, the implemented
methods to do parallel BO are described in

http://arxiv.org/pdf/1505.08052v4.pdf

In the manual of the devel branch we have more details but it is not
finished yet.

Thanks for the interest!

**Comment by iaroslav-ai** [comment]
Great, thanks for such a rapid feedback! :D

**Comment by javiergonzalezh** [comment]
Thanks to you for contributing!
