### ISSUE TITLE
GPModel X_new/Y_new unused?

### ISSUE THREAD

**Issue by 1Reinier** [SheffieldML/GPyOpt#90]
I'm implementing my own `BOModel`. I see that none of the models inheriting from `GPyOpt.models.base.BOModel` (including GPModel) do anything with the `X_new` and `Y_new` arguments in `updateModel(self, X_all, Y_all, X_new, Y_new)`.

Why is this the case?

The core BO object does try to call `updateModel(self, X_all, Y_all, X_new, Y_new)` with all arguments.

Is that a problem?

**Comment by javiergonzalezh** [comment]
We had some discussions about this. In principle X_all and Y_all are used in most cases (all we have in the current framework). X_new and Y_new are there in case you have a model that you want to by just augmenting it with the new collected data. It shouldn't be a problem if you don't use it, just think about it like a door we kept open to cover that potential case.

**Comment by 1Reinier** [comment]
Thanks
