### ISSUE TITLE
I have an error when I specify my new model!

### ISSUE THREAD

**Issue by Roston1** [SheffieldML/GPyOpt#91]
I created my own model, However, when I specify my model type= New model it gives me this error!

import sys
sys.path.append("/homes/mpd37/research/git/icl-sml/gptf")

from GPyOpt.models.base import BOModel
import numpy as np

# import appropriate classes from gptf
from gptf.gpr import GPR
from gptf.distributed import gPoEReduction, equal_weights

# define class for use with GPyOpt
class TFgPoEModel(BOModel):
   
    """
    Creates a new GPyOpt model using ``gptf.distributed.gPoEReduction``
    as a back end.

    :param normalize Y: wheter the outputs are normalized (default, false)

    """

    # SET THIS LINE TO True of False DEPENDING IN THE ANALYTICAL GRADIENTS OF THE PREDICTIONS ARE AVAILABLE OR NOT
  
    analytical_gradient_prediction = False

    def __init__(self, normalize_Y=True, num_experts=1):
        self.normalize_Y = normalize_Y
        # self.model = None  ---> not sure why we need this?

        # add a parameter for the number of expert models
        self.num_experts = num_experts

    def _create_model(self, X, Y):
        """
        Creates the model given some input data X and Y.
        """
        self.X = X
        self.Y = Y
        
        # create experts for the new model
        experts = (GPR()) * self.num_experts

        # create the model
        self.model = gPoEReduction(experts, equal_weights)
        
    def updateModel(self, X_all, Y_all, X_new, Y_new):
        """
        Updates the model with new observations.
        """    
        X_all = np.vstack(X_all, X_new)
        Y_all = np.vstack(Y_all, Y_new)
        
        if self.normalize_Y:
            Y_all = (Y_all - Y_all.mean())/(Y_all.std())

        self.X = X_all
        self.Y = Y_all
        
        
        if self.model is None: 
            self._create_model(self.X, self.Y)
        else: 
            self.model.optimize(self.X, self.Y)
                 
    def predict(self, Xstar):
        """
        Preditions with the model. Returns posterior means m and standard deviations s at X. 
        """
        mean, variance = self.model.compute_posterior_mean_var(self.X, self.Y, Xstar)
        std_dev = np.sqrt(variance)

        return mean, std_dev
    
    
    def get_fmin(self):
        #calculuate the minimum of the posterior
         return self.model.predict(self.model.X)[0].min()

Now I Specify my model type:

ROpt = GPyOpt.methods.BayesianOptimization(f_sim.f,
                                              domain=bounds,
                                              model_type = 'TFgPoEModel',
                                              acquisition_type='EI',  
                                              normalize_Y = True,
                                              acquisition_weight = 2)  

  I have this error:
AttributeError: 'NoneType' object has no attribute 'analytical_gradient_prediction'

Is there anyway I could fix this problem, What am I doing wrong. I set the analytical gradient to False!

**Comment by zhenwendai** [comment]
The BayesianOptimization cannot automotically understand the new surrogate model. Try to the following argument:
```python
m = TFgPoEModel()
ROpt = GPyOpt.methods.BayesianOptimization(f_sim.f,
domain=bounds,
model = m,
acquisition_type='EI',
normalize_Y = True,
acquisition_weight = 2)
```

**Comment by javiergonzalezh** [comment]
That's right,```model_type``` is a flag to the existing models but ```model``` allows you to pass directly the class. Also you can use the [modular interface ](http://nbviewer.jupyter.org/github/SheffieldML/GPyOpt/blob/devel/manual/GPyOpt_modular_bayesian_optimization.ipynb) for this where you only pass instances of the elements that you need for the optimization.

Hope this help!
