### ISSUE TITLE
How max_iter works in function  run_optimization (max_iter)?

### ISSUE THREAD

**Issue by yangxiufengsia** [SheffieldML/GPyOpt#92]

**Comment by yangxiufengsia** [comment]
from GPyOpt.methods import BayesianOptimization
import GPyOpt
import random

def myf(x):
    print x
    return (2*x)**2
def f(X):
    #x0=X[:,0]
    #y=x0+2
    print X
    return (2*X)**2


bounds = [{'name': 'x0', 'type': 'continuous', 'domain': (0,10)}]

myProblem = GPyOpt.methods.BayesianOptimization(f=myf,domain=bounds)
max_iter=1000
                                                    
myProblem.run_optimization(max_iter)
print "x:",myProblem.x_opt
print "y:",myProblem.fx_opt


This is my script,  I set max_iter=1000, but the BO stops at about 20 iterations. Can you tell me why is this?

**Comment by yangxiufengsia** [comment]
[[ 0.65609356]]
[[ 5.30561704]]
[[ 7.22145334]]
[[ 1.45408461]]
[[ 1.42369684]]
[[ 0.]]
[[ 0.23692409]]
[[ 0.40841713]]
[[ 0.10283573]]
[[ 2.68213483]]
[[ 0.92556002]]
[[ 9.99756369]]
[[ 2.00634399]]
[[ 3.69233233]]
[[ 0.52368505]]
[[ 0.3165883]]
[[ 1.12568231]]
[[ 0.16677393]]
[[ 0.04836512]]
[[ 0.90097452]]
[[ 0.90097452]]
x: [ 0.]
y: [ 0.]

**Comment by yangxiufengsia** [comment]
If I change the range of domain (0,10) to (-1,1) it will work fine. But what is the reason?

**Comment by tpsanjan** [comment]
As you can see the last two values sampled by bayes_opt are the same 0.90097452. For your example function 2(x^2), minima lies at x,y = (0,0) which has been found within 20 iters (after all the idea of bayes opt is to find in minimum possible iterations). 
In general, you could try a smaller tolerance value (i.e. eps) for more precision, in case you are not satisfied with the current performance of ML model or hyper-parameter tuning.

**Comment by yangxiufengsia** [comment]
Thanks for your detailed answer. In general, we don't know the minimum or maximum of the objective function. In that case, how to specify the value of maxi-iter? Gpyopt still stops at some certain iterations? Because as I test, it will stops without following the max-iter.

**Comment by javiergonzalezh** [comment]
In the new pre-release (still in devel), you have the option of using a de_duplication manager, which controls whether you allow for repeated measurements at the same point or not. This should solve this issue.
