### ISSUE TITLE
Does non-myopic BO penalizes the cost at each stage (i.e., iteration)?

### ISSUE THREAD

**Issue by AliBaheri** [SheffieldML/GPyOpt#97]
Hi Javier!

We are trying to get benefit form GLASSES algorithm to design a real-time controller in a length of a long horizon. We have adopted the GLASSES with our problem and have some reasonable results. However, the main concerns is :
 
Is there any notion of stage cost in non-myopic Bayesian optimization? In other words, does performance being penalized in all n-steps ahead? We realize that the acquisition is being penalized in all steps by a local penalizer, but we can not distinct that this penalization is the same as stage cost (in the traditional way of our control method, the cost is formulated as the expected value of the sum of discounted cost-per stage).
(of course the paper clearly states why you have used this local penalization in GLASSES algorithm.) 

We guess as an optimal design problem (in opposed to optimal control problem), the expected loss in GLASSES does only "cares about" the best performance in the horizon, rather than the overall performance throughout the horizon. Does it correct?

**Comment by javiergonzalezh** [comment]
Hi Ali, that's correct. GLASSES is designed to provide the best result at the end of the optimization. This means that you may do worse than the EI at the first iterations, but you should expect a better result at the end.

Regarding the cost: as GLASSES is non-myopic, it automatically balances exploration and exploration by taking into account the number of remaining evaluations, but no explicit use of cost is done. This is definitely a good point though!
