### ISSUE TITLE
I found a bug in bo.py

### ISSUE THREAD

**Issue by benavoli** [SheffieldML/GPyOpt#98]
Hi,

I have found a bug in bo.py:

"if self.model_parameters_iterations == None:"

should be (I think)

"if np.any(self.model_parameters_iterations == None):"

Best,
Alessio

**Comment by jzpgit** [comment]
#96 See my comments. Another possible solution.

**Comment by javiergonzalezh** [comment]
This has been updated in the new pre-release (still in the devel branch)
